//! Monomial ideals: their combinatorial data, and their field-free analysis.
//!
//! A monomial ideal of `kQ` is generated by paths. Its data is the quiver and
//! the forbidden words, and nothing about it depends on the field.
//! [`MonomialIdeal`] carries that data, validated and reduced to the minimal
//! generators. [`MonomialPresentation`] adds the analysis: the standard-path
//! basis, the exact finiteness decision, and the Cartan matrix, all before a
//! field is chosen.
//!
//! Neither type builds a runtime algebra. Building one goes through
//! [`crate::algebra::monomial_presentation`], which turns a
//! [`MonomialIdeal`] into a [`crate::relation::Presentation`] over a field,
//! and then through the one completion and verification pipeline every
//! algebra uses. The basis this module computes and the normal-word basis
//! that pipeline computes agree word for word, because for a monomial ideal
//! the standard paths are exactly the normal words.
//!
//! The named families live here: linearly oriented `A_n`, Kronecker,
//! `k[x]/(xⁿ)`, linear and cyclic Nakayama, the radical-square-zero cycle,
//! and `A_n` with zero relations. Each returns a [`MonomialIdeal`];
//! [`crate::algebra`] has the matching runtime constructor.

use std::fmt;

use rustc_hash::{FxHashMap, FxHashSet};

use crate::quiver::{ArrowId, PathWord, Quiver, QuiverError};

/// Rejected input to a monomial constructor.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MonomialError {
    /// Forbidden word `index` has length < 2. Admissibility needs `I ⊆ J²`.
    ForbiddenWordTooShort { index: usize, len: usize },
    /// Forbidden word `index` is not a path in the quiver.
    ForbiddenWordInvalid { index: usize, error: QuiverError },
    /// The standard-path language is infinite; this crate supports
    /// finite-dimensional algebras only.
    InfiniteDimensional,
    /// The Kupisch series breaks a condition of [`linear_nakayama_ideal`] or
    /// [`cyclic_nakayama_ideal`]; `reason` names the condition.
    InvalidKupisch { reason: String },
    /// No path with this start and length exists in the linear quiver.
    ZeroPathOutOfRange { start: usize, len: usize },
}

impl fmt::Display for MonomialError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ForbiddenWordTooShort { index, len } => write!(
                f,
                "forbidden word {index} has length {len}; admissibility needs length >= 2"
            ),
            Self::ForbiddenWordInvalid { index, error } => {
                write!(f, "forbidden word {index} is not a path: {error}")
            }
            Self::InfiniteDimensional => f.write_str(
                "the standard-path language is infinite; this crate supports finite-dimensional algebras only",
            ),
            Self::InvalidKupisch { reason } => write!(f, "invalid Kupisch series: {reason}"),
            Self::ZeroPathOutOfRange { start, len } => write!(
                f,
                "no path of length {len} starting at vertex {start} in the linear quiver"
            ),
        }
    }
}

impl std::error::Error for MonomialError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::ForbiddenWordInvalid { error, .. } => Some(error),
            _ => None,
        }
    }
}

/// A monomial ideal as field-free data: the quiver and the minimal forbidden
/// words.
///
/// The words are composable paths of length >= 2, sorted by length then
/// lexicographically, with duplicates and words containing another forbidden
/// word dropped. That reduction leaves the generated ideal unchanged, and it
/// fixes the relation order every downstream construction sees.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct MonomialIdeal {
    quiver: Quiver,
    forbidden: Vec<Vec<ArrowId>>,
}

impl MonomialIdeal {
    /// Validates `forbidden` against `quiver` and reduces it to the minimal
    /// generators.
    ///
    /// Errors with [`MonomialError::ForbiddenWordTooShort`] for a word of
    /// length < 2 and [`MonomialError::ForbiddenWordInvalid`] for a word that
    /// does not compose in `quiver`. Both name the index in the input list,
    /// before the reduction reorders anything.
    pub fn new(
        quiver: Quiver,
        forbidden: Vec<Vec<ArrowId>>,
    ) -> Result<MonomialIdeal, MonomialError> {
        for (index, word) in forbidden.iter().enumerate() {
            if word.len() < 2 {
                return Err(MonomialError::ForbiddenWordTooShort {
                    index,
                    len: word.len(),
                });
            }
            if let Err(error) = PathWord::from_arrows(&quiver, word) {
                return Err(MonomialError::ForbiddenWordInvalid { index, error });
            }
        }
        Ok(MonomialIdeal {
            quiver,
            forbidden: minimal_words(forbidden),
        })
    }

    #[inline]
    pub fn quiver(&self) -> &Quiver {
        &self.quiver
    }

    /// The minimal forbidden words, sorted by length then arrow word.
    #[inline]
    pub fn forbidden(&self) -> &[Vec<ArrowId>] {
        &self.forbidden
    }
}

/// The field-free combinatorics of a [`MonomialIdeal`]: the standard-path
/// basis of `kQ/I` and the Cartan matrix, before a field is chosen.
///
/// A standard path is a path containing no forbidden word as a contiguous
/// factor. Construction either certifies that the standard-path language is
/// finite or fails. The basis order matches the normal-word order of
/// [`crate::algebra::Algebra`]: `basis[v]` is the trivial path `e_v` for
/// `v < num_vertices`; the remaining entries are sorted by length, then
/// source vertex, then lexicographic arrow word.
///
/// This type analyzes; it does not construct. Build the runtime algebra over
/// a field from the [`MonomialIdeal`] with
/// [`crate::algebra::monomial_presentation`] and
/// [`crate::algebra::Algebra::new`].
///
/// ```
/// use auslander::monomial::{MonomialIdeal, MonomialPresentation};
/// use auslander::quiver::{ArrowId, Quiver};
/// let loop_x = Quiver::new(1, &[(0, 0)]).unwrap();
/// let ideal = MonomialIdeal::new(loop_x, vec![vec![ArrowId(0); 2]]).unwrap();
/// let m = MonomialPresentation::new(ideal).unwrap();
/// assert_eq!(m.dim(), 2); // k[x]/(x²): basis e, x
/// ```
#[derive(Clone, Debug)]
pub struct MonomialPresentation {
    ideal: MonomialIdeal,
    basis: Vec<PathWord>,
}

impl MonomialPresentation {
    /// Enumerates the standard-path basis of `kQ/ideal`.
    ///
    /// Errors with [`MonomialError::InfiniteDimensional`] when the
    /// standard-path language is infinite. Cycle detection on the
    /// forbidden-prefix automaton decides this exactly.
    pub fn new(ideal: MonomialIdeal) -> Result<MonomialPresentation, MonomialError> {
        let automaton = Automaton::build(&ideal.quiver, &ideal.forbidden);
        if automaton.has_cycle() {
            return Err(MonomialError::InfiniteDimensional);
        }
        let quiver = &ideal.quiver;
        let n = quiver.num_vertices() as usize;
        let mut basis: Vec<PathWord> = (0..quiver.num_vertices())
            .map(PathWord::trivial_unchecked)
            .collect();
        let mut state: Vec<usize> = (0..n).collect();
        let mut level_start = 0;
        while level_start < basis.len() {
            let level_end = basis.len();
            for i in level_start..level_end {
                let word = basis[i].arrows().to_vec();
                let target = basis[i].target();
                let s = state[i];
                for &a in quiver.arrows_from(target) {
                    if let Some(next) = automaton.step(s, a) {
                        let mut extended = word.clone();
                        extended.push(a);
                        basis.push(PathWord::from_arrows_unchecked(quiver, extended));
                        state.push(next);
                    }
                }
            }
            level_start = level_end;
        }
        Ok(MonomialPresentation { ideal, basis })
    }

    /// The ideal this presentation analyzes.
    #[inline]
    pub fn ideal(&self) -> &MonomialIdeal {
        &self.ideal
    }

    #[inline]
    pub fn quiver(&self) -> &Quiver {
        self.ideal.quiver()
    }

    /// The minimal forbidden words, sorted by length then arrow word.
    #[inline]
    pub fn forbidden(&self) -> &[Vec<ArrowId>] {
        self.ideal.forbidden()
    }

    /// `dim_k A` = number of standard paths, the same over every field.
    #[inline]
    pub fn dim(&self) -> usize {
        self.basis.len()
    }

    /// The standard-path basis, in the order documented on the type.
    #[inline]
    pub fn basis(&self) -> &[PathWord] {
        &self.basis
    }

    /// Cartan matrix: `c[i][j] = dim e_i A e_j`, the number of standard
    /// paths from `i` to `j`; row `i` is the dimension vector of the
    /// projective `P_i = e_i A`.
    pub fn cartan_matrix(&self) -> Vec<Vec<usize>> {
        let n = self.quiver().num_vertices() as usize;
        let mut cartan = vec![vec![0usize; n]; n];
        for path in &self.basis {
            cartan[path.source() as usize][path.target() as usize] += 1;
        }
        cartan
    }
}

/// Drops duplicate words and words containing another as a contiguous factor;
/// the generated ideal is unchanged. The result is sorted by length, then
/// lexicographically.
fn minimal_words(mut words: Vec<Vec<ArrowId>>) -> Vec<Vec<ArrowId>> {
    words.sort();
    words.dedup();
    words.sort_by_key(Vec::len);
    let mut minimal: Vec<Vec<ArrowId>> = Vec::new();
    for word in words {
        let contains_kept = minimal
            .iter()
            .any(|v| word.windows(v.len()).any(|w| w == v.as_slice()));
        if !contains_kept {
            minimal.push(word);
        }
    }
    minimal
}

/// Deterministic automaton recognizing standard paths.
///
/// States `v < num_vertices`: "at vertex `v`, no forbidden-word progress".
/// Remaining states: the nonempty proper prefixes of the (minimal) forbidden
/// words. The state after reading a standard path is its longest suffix that
/// is such a prefix. A transition is absent exactly when the arrow does not
/// start at the state's vertex, or when appending it completes a forbidden
/// word. Minimality of the forbidden set guarantees that no prefix state
/// contains a forbidden factor, so every state is reachable from a start
/// state. Any cycle then proves the standard-path language infinite.
struct Automaton {
    trans: Vec<Vec<Option<usize>>>,
}

impl Automaton {
    fn build(quiver: &Quiver, forbidden: &[Vec<ArrowId>]) -> Automaton {
        let n = quiver.num_vertices() as usize;
        let mut prefixes: Vec<Vec<ArrowId>> = Vec::new();
        let mut prefix_index: FxHashMap<Vec<ArrowId>, usize> = FxHashMap::default();
        for word in forbidden {
            for len in 1..word.len() {
                let prefix = word[..len].to_vec();
                if !prefix_index.contains_key(&prefix) {
                    prefix_index.insert(prefix.clone(), prefixes.len());
                    prefixes.push(prefix);
                }
            }
        }
        let forbidden_set: FxHashSet<&[ArrowId]> = forbidden.iter().map(Vec::as_slice).collect();

        let num_states = n + prefixes.len();
        let mut trans = vec![vec![None; quiver.num_arrows()]; num_states];
        for (s, row) in trans.iter_mut().enumerate() {
            let (word, vertex): (&[ArrowId], u32) = if s < n {
                (&[], s as u32)
            } else {
                let w = prefixes[s - n].as_slice();
                (w, quiver.target(w[w.len() - 1]))
            };
            for &a in quiver.arrows_from(vertex) {
                let mut extended = word.to_vec();
                extended.push(a);
                // Longest suffix in (forbidden ∪ prefixes) decides; minimality makes
                // the two sets disjoint and rules out shorter forbidden suffixes
                // hiding under a prefix match.
                let mut next = Some(quiver.target(a) as usize);
                for start in 0..extended.len() {
                    let suffix = &extended[start..];
                    if forbidden_set.contains(suffix) {
                        next = None;
                        break;
                    }
                    if let Some(&k) = prefix_index.get(suffix) {
                        next = Some(n + k);
                        break;
                    }
                }
                row[a.index()] = next;
            }
        }
        Automaton { trans }
    }

    /// Kahn's algorithm. Every state is reachable, so a cycle means
    /// infinitely many standard paths.
    fn has_cycle(&self) -> bool {
        let m = self.trans.len();
        let mut indegree = vec![0usize; m];
        for row in &self.trans {
            for &t in row.iter().flatten() {
                indegree[t] += 1;
            }
        }
        let mut stack: Vec<usize> = (0..m).filter(|&s| indegree[s] == 0).collect();
        let mut visited = 0;
        while let Some(s) = stack.pop() {
            visited += 1;
            for &t in self.trans[s].iter().flatten() {
                indegree[t] -= 1;
                if indegree[t] == 0 {
                    stack.push(t);
                }
            }
        }
        visited < m
    }

    #[inline]
    fn step(&self, s: usize, a: ArrowId) -> Option<usize> {
        self.trans[s][a.index()]
    }
}

/// Linearly oriented `A_n`: vertices `0..n`, arrows `i → i+1`.
pub fn linear_quiver(n: usize) -> Quiver {
    let n = u32::try_from(n).expect("vertex count fits in u32");
    let arrows: Vec<(u32, u32)> = (0..n.saturating_sub(1)).map(|i| (i, i + 1)).collect();
    Quiver::new(n, &arrows).expect("endpoints in range by construction")
}

/// The cycle `0 → 1 → … → n-1 → 0`.
pub fn cyclic_quiver(n: usize) -> Quiver {
    let arrows: Vec<(u32, u32)> = (0..n).map(|i| (i as u32, ((i + 1) % n) as u32)).collect();
    Quiver::new(u32::try_from(n).expect("vertex count fits in u32"), &arrows)
        .expect("endpoints in range by construction")
}

/// Linearly oriented `A_n` with no relations. Runtime form:
/// [`crate::algebra::linear_an`].
pub fn linear_an_ideal(n: usize) -> MonomialIdeal {
    MonomialIdeal::new(linear_quiver(n), Vec::new()).expect("there is no forbidden word to reject")
}

/// Vertices `0, 1` and `m` parallel arrows `0 → 1`, no relations. Runtime
/// form: [`crate::algebra::kronecker`].
pub fn kronecker_ideal(m: usize) -> MonomialIdeal {
    let arrows = vec![(0u32, 1u32); m];
    let quiver = Quiver::new(2, &arrows).expect("endpoints in range by construction");
    MonomialIdeal::new(quiver, Vec::new()).expect("there is no forbidden word to reject")
}

/// `k[x]/(xⁿ)`: one vertex, one loop `x`, forbidden word `xⁿ`. Errors for
/// `n < 2` (the ideal would not be admissible). Runtime form:
/// [`crate::algebra::truncated_poly`].
pub fn truncated_poly_ideal(n: usize) -> Result<MonomialIdeal, MonomialError> {
    let quiver = Quiver::new(1, &[(0, 0)]).expect("endpoints in range by construction");
    MonomialIdeal::new(quiver, vec![vec![ArrowId(0); n]])
}

/// The linear Nakayama ideal over linearly oriented `A_n` with
/// `dim P_i = kupisch[i]`.
///
/// Valid series `c`: nonempty; `c[n-1] == 1`; `c[i] >= 2` for `i < n-1`
/// (admissibility); `c[i+1] >= c[i] - 1` (rad `P_i` is a quotient of
/// `P_{i+1}`). Anything else errors; for example `[3, 3, 2]`, where no
/// admissible ideal gives the prescribed projective dimensions. Runtime
/// form: [`crate::algebra::linear_nakayama`].
pub fn linear_nakayama_ideal(kupisch: &[usize]) -> Result<MonomialIdeal, MonomialError> {
    let n = kupisch.len();
    if n == 0 {
        return Err(MonomialError::InvalidKupisch {
            reason: "series is empty".to_string(),
        });
    }
    if kupisch[n - 1] != 1 {
        return Err(MonomialError::InvalidKupisch {
            reason: format!(
                "linear series must end with 1, got c[{}] = {}",
                n - 1,
                kupisch[n - 1]
            ),
        });
    }
    for i in 0..n - 1 {
        if kupisch[i] < 2 {
            return Err(MonomialError::InvalidKupisch {
                reason: format!("c[{i}] = {} but interior entries need c >= 2", kupisch[i]),
            });
        }
        if kupisch[i + 1] < kupisch[i] - 1 {
            return Err(MonomialError::InvalidKupisch {
                reason: format!(
                    "c[{}] = {} violates c[i+1] >= c[i] - 1 = {}",
                    i + 1,
                    kupisch[i + 1],
                    kupisch[i] - 1
                ),
            });
        }
    }
    let mut forbidden = Vec::new();
    for (i, &c) in kupisch.iter().enumerate() {
        // Forbid the path from i of length c; it exists only when
        // i + c <= n - 1.
        if i + c <= n - 1 {
            forbidden.push((i..i + c).map(|j| ArrowId(j as u32)).collect());
        }
    }
    MonomialIdeal::new(linear_quiver(n), forbidden)
}

/// The cyclic Nakayama ideal over the cycle `0 → 1 → … → n-1 → 0` with
/// `dim P_i = kupisch[i]`.
///
/// Valid series `c`: nonempty; `c[i] >= 2` for all `i` (admissibility);
/// cyclically `c[(i+1) % n] >= c[i] - 1`. Anything else errors. Runtime form:
/// [`crate::algebra::cyclic_nakayama`].
pub fn cyclic_nakayama_ideal(kupisch: &[usize]) -> Result<MonomialIdeal, MonomialError> {
    let n = kupisch.len();
    if n == 0 {
        return Err(MonomialError::InvalidKupisch {
            reason: "series is empty".to_string(),
        });
    }
    for (i, &c) in kupisch.iter().enumerate() {
        if c < 2 {
            return Err(MonomialError::InvalidKupisch {
                reason: format!("c[{i}] = {c} but cyclic entries need c >= 2"),
            });
        }
        if kupisch[(i + 1) % n] < c - 1 {
            return Err(MonomialError::InvalidKupisch {
                reason: format!(
                    "c[{}] = {} violates cyclic c[i+1] >= c[i] - 1 = {}",
                    (i + 1) % n,
                    kupisch[(i + 1) % n],
                    c - 1
                ),
            });
        }
    }
    let forbidden: Vec<Vec<ArrowId>> = (0..n)
        .map(|i| {
            (0..kupisch[i])
                .map(|j| ArrowId(((i + j) % n) as u32))
                .collect()
        })
        .collect();
    MonomialIdeal::new(cyclic_quiver(n), forbidden)
}

/// The cyclic quiver on `n` vertices with `rad² = 0`: every length-2 path
/// forbidden. `dim = 2n`. Runtime form:
/// [`crate::algebra::radical_square_zero_cycle`].
pub fn radical_square_zero_cycle_ideal(n: usize) -> MonomialIdeal {
    let forbidden: Vec<Vec<ArrowId>> = (0..n)
        .map(|i| vec![ArrowId(i as u32), ArrowId(((i + 1) % n) as u32)])
        .collect();
    MonomialIdeal::new(cyclic_quiver(n), forbidden).expect("a length-2 path is a valid word")
}

/// Linearly oriented `A_n` with zero relations: each `(start, len)` in
/// `zero_paths` kills the unique path of length `len` from vertex `start`
/// (arrows `start, …, start + len - 1`). `kA_3/(ab)` is
/// `an_with_relations_ideal(3, &[(0, 2)])`.
///
/// Errors when a zero path runs past vertex `n - 1` or has length < 2.
/// Runtime form: [`crate::algebra::an_with_relations`].
pub fn an_with_relations_ideal(
    n: usize,
    zero_paths: &[(usize, usize)],
) -> Result<MonomialIdeal, MonomialError> {
    for &(start, len) in zero_paths {
        if n == 0 || start + len > n - 1 {
            return Err(MonomialError::ZeroPathOutOfRange { start, len });
        }
    }
    let forbidden = zero_paths
        .iter()
        .map(|&(start, len)| (start..start + len).map(|j| ArrowId(j as u32)).collect())
        .collect();
    MonomialIdeal::new(linear_quiver(n), forbidden)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn present(quiver: Quiver, forbidden: Vec<Vec<ArrowId>>) -> MonomialPresentation {
        MonomialPresentation::new(MonomialIdeal::new(quiver, forbidden).unwrap()).unwrap()
    }

    #[test]
    fn loop_without_relations_is_infinite_dimensional() {
        let quiver = Quiver::new(1, &[(0, 0)]).unwrap();
        let ideal = MonomialIdeal::new(quiver, Vec::new()).unwrap();
        assert_eq!(
            MonomialPresentation::new(ideal).unwrap_err(),
            MonomialError::InfiniteDimensional
        );
    }

    #[test]
    fn cycle_without_relations_is_infinite_dimensional() {
        let quiver = Quiver::new(3, &[(0, 1), (1, 2), (2, 0)]).unwrap();
        let ideal = MonomialIdeal::new(quiver, Vec::new()).unwrap();
        assert_eq!(
            MonomialPresentation::new(ideal).unwrap_err(),
            MonomialError::InfiniteDimensional
        );
    }

    #[test]
    fn two_loops_with_xx_yy_forbidden_is_infinite() {
        // xyxyxy… never contains xx or yy, so the automaton must find the cycle.
        let quiver = Quiver::new(1, &[(0, 0), (0, 0)]).unwrap();
        let ideal = MonomialIdeal::new(
            quiver,
            vec![vec![ArrowId(0), ArrowId(0)], vec![ArrowId(1), ArrowId(1)]],
        )
        .unwrap();
        assert_eq!(
            MonomialPresentation::new(ideal).unwrap_err(),
            MonomialError::InfiniteDimensional
        );
    }

    #[test]
    fn two_loops_with_rad_square_zero_has_dim_3() {
        let quiver = Quiver::new(1, &[(0, 0), (0, 0)]).unwrap();
        let forbidden = vec![
            vec![ArrowId(0), ArrowId(0)],
            vec![ArrowId(0), ArrowId(1)],
            vec![ArrowId(1), ArrowId(0)],
            vec![ArrowId(1), ArrowId(1)],
        ];
        assert_eq!(present(quiver, forbidden).dim(), 3);
    }

    #[test]
    fn forbidden_words_reduced_to_minimal() {
        // A4 with both ab and abc: abc contains ab, so only ab survives.
        let quiver = Quiver::new(4, &[(0, 1), (1, 2), (2, 3)]).unwrap();
        let m = present(
            quiver,
            vec![
                vec![ArrowId(0), ArrowId(1), ArrowId(2)],
                vec![ArrowId(0), ArrowId(1)],
            ],
        );
        assert_eq!(m.forbidden(), &[vec![ArrowId(0), ArrowId(1)]]);
        assert_eq!(m.dim(), 8); // e0..e3, a, b, c, bc
    }

    #[test]
    fn forbidden_word_too_short_rejected() {
        let quiver = Quiver::new(2, &[(0, 1)]).unwrap();
        assert_eq!(
            MonomialIdeal::new(quiver, vec![vec![ArrowId(0)]]).unwrap_err(),
            MonomialError::ForbiddenWordTooShort { index: 0, len: 1 }
        );
    }

    #[test]
    fn forbidden_word_not_composable_rejected() {
        let quiver = Quiver::new(3, &[(0, 1), (1, 2)]).unwrap();
        assert_eq!(
            MonomialIdeal::new(quiver, vec![vec![ArrowId(1), ArrowId(0)]]).unwrap_err(),
            MonomialError::ForbiddenWordInvalid {
                index: 0,
                error: QuiverError::NotComposable { position: 0 },
            }
        );
    }

    #[test]
    fn linear_a3_basis_and_cartan() {
        let m = MonomialPresentation::new(linear_an_ideal(3)).unwrap();
        assert_eq!(m.dim(), 6);
        assert_eq!(
            m.cartan_matrix(),
            vec![vec![1, 1, 1], vec![0, 1, 1], vec![0, 0, 1]]
        );
        let lengths: Vec<usize> = m.basis().iter().map(PathWord::len).collect();
        assert_eq!(lengths, vec![0, 0, 0, 1, 1, 2]);
    }

    #[test]
    fn named_family_dimensions() {
        let dim = |ideal| MonomialPresentation::new(ideal).unwrap().dim();
        assert_eq!(dim(kronecker_ideal(2)), 4);
        assert_eq!(dim(truncated_poly_ideal(3).unwrap()), 3);
        assert_eq!(dim(linear_nakayama_ideal(&[2, 2, 1]).unwrap()), 5);
        assert_eq!(dim(cyclic_nakayama_ideal(&[3, 3, 3]).unwrap()), 9);
        assert_eq!(dim(radical_square_zero_cycle_ideal(3)), 6);
        assert_eq!(dim(an_with_relations_ideal(3, &[(0, 2)]).unwrap()), 5);
    }

    #[test]
    fn invalid_family_parameters_rejected() {
        assert!(matches!(
            truncated_poly_ideal(1),
            Err(MonomialError::ForbiddenWordTooShort { index: 0, len: 1 })
        ));
        for kupisch in [&[3, 3, 2][..], &[4, 2, 1][..]] {
            assert!(matches!(
                linear_nakayama_ideal(kupisch),
                Err(MonomialError::InvalidKupisch { .. })
            ));
        }
        for kupisch in [&[2, 1, 2][..], &[4, 2, 2][..]] {
            assert!(matches!(
                cyclic_nakayama_ideal(kupisch),
                Err(MonomialError::InvalidKupisch { .. })
            ));
        }
        assert_eq!(
            an_with_relations_ideal(3, &[(1, 2)]).unwrap_err(),
            MonomialError::ZeroPathOutOfRange { start: 1, len: 2 }
        );
    }
}
