//! Python façade for the `auslander` crate: prime fields, quivers, monomial bound
//! quiver algebras, and their right modules.
//!
//! The surface is deliberately small and algebra-owned: modules are only ever
//! created through `MonomialAlgebra` methods, so every Python-visible `Module` is a
//! validated `kQ/I`-module. Library errors cross the boundary as `ValueError`
//! carrying the Rust `Display` message.

use std::sync::Arc;

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

use auslander::algebra::{self, MonomialAlgebra};
use auslander::ext;
use auslander::field::PrimeField;
use auslander::hom;
use auslander::linalg::DenseMat;
use auslander::module::Module;
use auslander::quiver::{ArrowId, Quiver};
use auslander::radical;
use auslander::resolution::{Bounded, ResolutionEnd, projective_dimension, resolve};

fn value_error(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}

/// One matrix from a list of integer rows, entries reduced mod p. A matrix given
/// as zero rows carries no column count of its own, so `cols_when_empty` supplies
/// the expected one; raises ValueError on rows of differing lengths.
fn dense_from_rows(
    field: PrimeField,
    rows: &[Vec<i64>],
    cols_when_empty: usize,
    what: &str,
) -> PyResult<DenseMat> {
    let cols = rows.first().map_or(cols_when_empty, Vec::len);
    let mut mat = DenseMat::zero(rows.len(), cols);
    for (r, row) in rows.iter().enumerate() {
        if row.len() != cols {
            return Err(PyValueError::new_err(format!(
                "{what} has rows of differing lengths ({} vs {cols})",
                row.len()
            )));
        }
        for (c, &v) in row.iter().enumerate() {
            mat.set(r, c, field.elem(v));
        }
    }
    Ok(mat)
}

/// The prime field F_p = Z/pZ.
///
/// Primality is checked at construction; p must be a prime below 2^31.
#[pyclass(name = "PrimeField", module = "auslander")]
struct PyPrimeField {
    inner: PrimeField,
}

#[pymethods]
impl PyPrimeField {
    /// F_p for a prime p < 2^31; raises ValueError otherwise.
    #[new]
    #[pyo3(text_signature = "(p)")]
    fn new(p: u64) -> PyResult<Self> {
        Ok(PyPrimeField {
            inner: PrimeField::new(p).map_err(value_error)?,
        })
    }

    /// The characteristic p.
    #[getter]
    fn p(&self) -> u64 {
        self.inner.modulus()
    }

    fn __repr__(&self) -> String {
        format!("PrimeField({})", self.inner.modulus())
    }
}

/// A finite quiver: vertices 0..num_vertices and a list of (source, target) arrows.
///
/// Arrow i of the list gets id i; forbidden words and module maps refer to arrows
/// by these ids. Paths compose left to right: the word [a, b] means "first a,
/// then b" and requires target(a) == source(b).
#[pyclass(name = "Quiver", module = "auslander")]
struct PyQuiver {
    inner: Quiver,
}

#[pymethods]
impl PyQuiver {
    /// A quiver on vertices 0..num_vertices with the given (source, target) arrows;
    /// raises ValueError when an endpoint is out of range.
    #[new]
    #[pyo3(text_signature = "(num_vertices, arrows)")]
    fn new(num_vertices: u32, arrows: Vec<(u32, u32)>) -> PyResult<Self> {
        Ok(PyQuiver {
            inner: Quiver::new(num_vertices, &arrows).map_err(value_error)?,
        })
    }

    fn __repr__(&self) -> String {
        format!(
            "Quiver(vertices={}, arrows={})",
            self.inner.num_vertices(),
            self.inner.num_arrows()
        )
    }
}

/// The monomial bound quiver algebra kQ/I, I generated by forbidden paths.
///
/// Forbidden words are lists of arrow ids, each of length >= 2 (admissibility) and
/// composable left to right. Construction certifies the standard-path basis finite
/// or raises ValueError, so `dim` and the Cartan matrix are exact. The algebra is
/// field-free; a field enters only when building modules, and modules can interact
/// (hom, ext) only when built from the same MonomialAlgebra object.
#[pyclass(name = "MonomialAlgebra", module = "auslander")]
struct PyAlgebra {
    inner: Arc<MonomialAlgebra>,
}

impl PyAlgebra {
    fn wrap(inner: Arc<MonomialAlgebra>) -> PyAlgebra {
        PyAlgebra { inner }
    }

    fn check_vertex(&self, v: u32) -> PyResult<()> {
        let n = self.inner.quiver().num_vertices();
        if v >= n {
            return Err(PyValueError::new_err(format!(
                "vertex {v} out of range: the quiver has vertices 0..{n}"
            )));
        }
        Ok(())
    }
}

#[pymethods]
impl PyAlgebra {
    /// kQ/(forbidden) with a certified finite standard-path basis; raises ValueError
    /// when a forbidden word is too short or not a path, or when the algebra would
    /// be infinite-dimensional.
    #[new]
    #[pyo3(text_signature = "(quiver, forbidden)")]
    fn new(quiver: &PyQuiver, forbidden: Vec<Vec<u32>>) -> PyResult<Self> {
        let forbidden: Vec<Vec<ArrowId>> = forbidden
            .into_iter()
            .map(|word| word.into_iter().map(ArrowId).collect())
            .collect();
        Ok(PyAlgebra::wrap(
            MonomialAlgebra::new(quiver.inner.clone(), forbidden).map_err(value_error)?,
        ))
    }

    /// Path algebra of linearly oriented A_n: vertices 0..n, arrows i -> i+1.
    #[staticmethod]
    #[pyo3(text_signature = "(n)")]
    fn linear_an(n: usize) -> PyAlgebra {
        PyAlgebra::wrap(algebra::linear_an(n))
    }

    /// Kronecker-type algebra: vertices 0, 1 and m parallel arrows 0 -> 1;
    /// hereditary, dim = m + 2.
    #[staticmethod]
    #[pyo3(text_signature = "(m)")]
    fn kronecker(m: usize) -> PyAlgebra {
        PyAlgebra::wrap(algebra::kronecker(m))
    }

    /// k[x]/(x^2): one vertex, one loop x, forbidden word xx.
    #[staticmethod]
    #[pyo3(text_signature = "()")]
    fn dual_numbers() -> PyAlgebra {
        PyAlgebra::wrap(algebra::dual_numbers())
    }

    /// k[x]/(x^n): one vertex, one loop x, forbidden word x^n; raises ValueError
    /// for n < 2 (the ideal would not be admissible).
    #[staticmethod]
    #[pyo3(text_signature = "(n)")]
    fn truncated_poly(n: usize) -> PyResult<PyAlgebra> {
        Ok(PyAlgebra::wrap(
            algebra::truncated_poly(n).map_err(value_error)?,
        ))
    }

    /// Linear Nakayama algebra over linearly oriented A_n with dim P_i = kupisch[i];
    /// raises ValueError on an invalid Kupisch series (needs kupisch[n-1] == 1,
    /// interior entries >= 2, and kupisch[i+1] >= kupisch[i] - 1).
    #[staticmethod]
    #[pyo3(text_signature = "(kupisch)")]
    fn linear_nakayama(kupisch: Vec<usize>) -> PyResult<PyAlgebra> {
        Ok(PyAlgebra::wrap(
            algebra::linear_nakayama(&kupisch).map_err(value_error)?,
        ))
    }

    /// Cyclic Nakayama algebra over the cycle 0 -> 1 -> ... -> n-1 -> 0 with
    /// dim P_i = kupisch[i]; raises ValueError on an invalid series (all entries
    /// >= 2 and cyclically kupisch[i+1] >= kupisch[i] - 1).
    #[staticmethod]
    #[pyo3(text_signature = "(kupisch)")]
    fn cyclic_nakayama(kupisch: Vec<usize>) -> PyResult<PyAlgebra> {
        Ok(PyAlgebra::wrap(
            algebra::cyclic_nakayama(&kupisch).map_err(value_error)?,
        ))
    }

    /// Cyclic quiver on n vertices with rad^2 = 0: every length-2 path forbidden;
    /// dim = 2n.
    #[staticmethod]
    #[pyo3(text_signature = "(n)")]
    fn radical_square_zero_cycle(n: usize) -> PyAlgebra {
        PyAlgebra::wrap(algebra::radical_square_zero_cycle(n))
    }

    /// Linearly oriented A_n with zero relations: each (start, length) pair kills
    /// the unique path of that length from vertex start. kA_3/(ab) is
    /// an_with_relations(3, [(0, 2)]). Raises ValueError when a zero path runs past
    /// the last vertex or has length < 2.
    #[staticmethod]
    #[pyo3(text_signature = "(n, zero_paths)")]
    fn an_with_relations(n: usize, zero_paths: Vec<(usize, usize)>) -> PyResult<PyAlgebra> {
        Ok(PyAlgebra::wrap(
            algebra::an_with_relations(n, &zero_paths).map_err(value_error)?,
        ))
    }

    /// dim_k of the algebra: the number of standard paths, trivial paths included.
    #[getter]
    fn dim(&self) -> usize {
        self.inner.dim()
    }

    /// Number of vertices of the underlying quiver.
    #[getter]
    fn num_vertices(&self) -> u32 {
        self.inner.quiver().num_vertices()
    }

    /// Number of arrows of the underlying quiver (the length `module` expects of
    /// its maps argument).
    #[getter]
    fn num_arrows(&self) -> usize {
        self.inner.quiver().num_arrows()
    }

    /// The Cartan matrix C with C[i][j] = dim e_i A e_j, the number of standard
    /// paths i -> j; row i is the dimension vector of the projective P_i.
    #[pyo3(text_signature = "($self)")]
    fn cartan_matrix(&self) -> Vec<Vec<usize>> {
        self.inner.cartan_matrix()
    }

    /// A right module from raw data: dims[v] is the dimension at vertex v, and
    /// maps[a] is a dims[source(a)] x dims[target(a)] integer matrix (list of rows)
    /// for arrow a, acting on row vectors; entries are reduced mod p. A path acts
    /// by the product of its arrow matrices in left-to-right word order. Raises
    /// ValueError when shapes disagree with the quiver or a forbidden word acts as
    /// a nonzero matrix.
    #[pyo3(text_signature = "($self, field, dims, maps)")]
    fn module(
        &self,
        field: &PyPrimeField,
        dims: Vec<usize>,
        maps: Vec<Vec<Vec<i64>>>,
    ) -> PyResult<PyRightModule> {
        let f = field.inner;
        let quiver = self.inner.quiver();
        let mut mats = Vec::with_capacity(maps.len());
        for (i, rows) in maps.iter().enumerate() {
            // The expected column count, so that e.g. dims [0, 1] accepts maps [[]].
            let cols = quiver
                .arrows()
                .get(i)
                .and_then(|&(_, t)| dims.get(t as usize).copied())
                .unwrap_or(0);
            mats.push(dense_from_rows(
                f,
                rows,
                cols,
                &format!("map for arrow {i}"),
            )?);
        }
        Ok(PyRightModule {
            inner: Module::new(self.inner.clone(), f, dims, mats).map_err(value_error)?,
        })
    }

    /// The simple module S_v: one-dimensional at v, zero elsewhere, all arrows
    /// acting as zero. Raises ValueError when v is not a vertex.
    #[pyo3(text_signature = "($self, field, v)")]
    fn simple(&self, field: &PyPrimeField, v: u32) -> PyResult<PyRightModule> {
        self.check_vertex(v)?;
        Ok(PyRightModule {
            inner: Module::simple(&self.inner, field.inner, v),
        })
    }

    /// The indecomposable projective P_v = e_v A: its basis at vertex w is the set
    /// of standard paths v -> w. Raises ValueError when v is not a vertex.
    #[pyo3(text_signature = "($self, field, v)")]
    fn projective(&self, field: &PyPrimeField, v: u32) -> PyResult<PyRightModule> {
        self.check_vertex(v)?;
        Ok(PyRightModule {
            inner: Module::projective(&self.inner, field.inner, v),
        })
    }

    /// The indecomposable injective I_v = D(A e_v): its basis at vertex w is dual
    /// to the standard paths w -> v. Raises ValueError when v is not a vertex.
    #[pyo3(text_signature = "($self, field, v)")]
    fn injective(&self, field: &PyPrimeField, v: u32) -> PyResult<PyRightModule> {
        self.check_vertex(v)?;
        Ok(PyRightModule {
            inner: Module::injective(&self.inner, field.inner, v),
        })
    }

    fn __repr__(&self) -> String {
        format!(
            "MonomialAlgebra(dim={}, vertices={})",
            self.inner.dim(),
            self.inner.quiver().num_vertices()
        )
    }
}

/// A finite-dimensional right kQ/I-module, validated at construction.
///
/// The module assigns to each vertex v the row-vector space k^dims[v] and to each
/// arrow a matrix acting on row vectors; paths act by matrix products in
/// left-to-right word order. Instances come only from MonomialAlgebra methods
/// (`module`, `simple`, `projective`, `injective`), and two modules can be compared
/// homologically only when they were built from the same MonomialAlgebra object
/// over equal fields.
#[pyclass(name = "Module", module = "auslander")]
struct PyRightModule {
    inner: Module,
}

fn check_same_context(m: &Module, n: &Module) -> PyResult<()> {
    if !Arc::ptr_eq(m.algebra(), n.algebra()) {
        return Err(PyValueError::new_err(
            "modules were built from different MonomialAlgebra objects; \
             hom and ext need both sides over the same algebra object",
        ));
    }
    if m.field() != n.field() {
        return Err(PyValueError::new_err(format!(
            "modules are over different fields F_{} and F_{}",
            m.field().modulus(),
            n.field().modulus()
        )));
    }
    Ok(())
}

#[pymethods]
impl PyRightModule {
    /// The dimension vector: dims[v] = dim_k M_v.
    #[getter]
    fn dims(&self) -> Vec<usize> {
        self.inner.dim_vector().to_vec()
    }

    /// The dimension vector; alias of `dims`.
    #[getter]
    fn dim_vector(&self) -> Vec<usize> {
        self.inner.dim_vector().to_vec()
    }

    /// dim_k M, the sum of the dimension vector.
    #[getter]
    fn total_dim(&self) -> usize {
        self.inner.total_dim()
    }

    /// A basis of Hom_A(self, other) as a list of Morphism objects, not every
    /// morphism: the hom space is a k-vector space and arbitrary morphisms are
    /// its linear combinations. Raises ValueError when the modules do not share
    /// one algebra object and field.
    #[pyo3(text_signature = "($self, other)")]
    fn hom(&self, other: &PyRightModule) -> PyResult<Vec<PyMorphism>> {
        check_same_context(&self.inner, &other.inner)?;
        let basis = hom::hom(&self.inner, &other.inner).map_err(value_error)?;
        Ok(basis
            .into_iter()
            .map(|inner| PyMorphism { inner })
            .collect())
    }

    /// A morphism self -> target from one dims_self[v] x dims_target[v] integer
    /// matrix (list of rows) per vertex, acting on row vectors; entries are
    /// reduced mod p. A-linearity (every commuting square) is checked; raises
    /// ValueError when shapes disagree, a square fails, or the modules do not
    /// share one algebra object and field.
    #[pyo3(text_signature = "($self, target, maps)")]
    fn morphism(&self, target: &PyRightModule, maps: Vec<Vec<Vec<i64>>>) -> PyResult<PyMorphism> {
        check_same_context(&self.inner, &target.inner)?;
        let field = self.inner.field();
        let mut mats = Vec::with_capacity(maps.len());
        for (v, rows) in maps.iter().enumerate() {
            let cols = target.inner.dim_vector().get(v).copied().unwrap_or(0);
            mats.push(dense_from_rows(
                field,
                rows,
                cols,
                &format!("map at vertex {v}"),
            )?);
        }
        Ok(PyMorphism {
            inner: hom::Morphism::new(&self.inner, &target.inner, mats).map_err(value_error)?,
        })
    }

    /// dim_k Hom_A(self, other). Raises ValueError when the modules do not share
    /// one algebra object and field.
    #[pyo3(text_signature = "($self, other)")]
    fn hom_dim(&self, other: &PyRightModule) -> PyResult<usize> {
        check_same_context(&self.inner, &other.inner)?;
        hom::hom_dim(&self.inner, &other.inner).map_err(value_error)
    }

    /// dim_k Ext^k_A(self, other), exact for every k; Ext^0 is Hom. Raises
    /// ValueError when the modules do not share one algebra object and field.
    #[pyo3(text_signature = "($self, other, k)")]
    fn ext_dim(&self, other: &PyRightModule, k: usize) -> PyResult<usize> {
        check_same_context(&self.inner, &other.inner)?;
        ext::ext_dim(&self.inner, &other.inner, k).map_err(value_error)
    }

    /// [dim Ext^0(self, other), ..., dim Ext^max_k(self, other)], each entry exact.
    /// Raises ValueError when the modules do not share one algebra object and field.
    #[pyo3(text_signature = "($self, other, max_k)")]
    fn ext_table(&self, other: &PyRightModule, max_k: usize) -> PyResult<Vec<usize>> {
        check_same_context(&self.inner, &other.inner)?;
        ext::ext_table(&self.inner, &other.inner, max_k).map_err(value_error)
    }

    /// Dimension vectors along the radical series M ⊇ rad M ⊇ rad^2 M ⊇ ...,
    /// ending with the zero module.
    #[pyo3(text_signature = "($self)")]
    fn radical_series_dims(&self) -> Vec<Vec<usize>> {
        radical::radical_series(&self.inner)
            .iter()
            .map(|m| m.dim_vector().to_vec())
            .collect()
    }

    /// The Loewy length: the least l with rad^l M = 0 (0 for the zero module).
    #[pyo3(text_signature = "($self)")]
    fn loewy_length(&self) -> usize {
        radical::loewy_length(&self.inner)
    }

    /// The dimension vector of top M = M / rad M.
    #[pyo3(text_signature = "($self)")]
    fn top_dims(&self) -> Vec<usize> {
        radical::top(&self.inner).0.dim_vector().to_vec()
    }

    /// The dimension vector of soc M, the largest submodule killed by the radical.
    #[pyo3(text_signature = "($self)")]
    fn socle_dims(&self) -> Vec<usize> {
        radical::socle(&self.inner).0.dim_vector().to_vec()
    }

    /// A minimal projective resolution prefix with at most `steps` differentials.
    /// The result records how it ended; see Resolution.status.
    #[pyo3(text_signature = "($self, steps)")]
    fn resolve(&self, steps: usize) -> PyResolution {
        let res = resolve(&self.inner, steps);
        PyResolution {
            module: self.inner.clone(),
            terms_dims: res.terms.iter().map(|t| t.dim_vector().to_vec()).collect(),
            end: res.end,
        }
    }

    fn __repr__(&self) -> String {
        format!(
            "Module(dims={:?}, field=F_{})",
            self.inner.dim_vector(),
            self.inner.field().modulus()
        )
    }
}

/// A basis element or checked construction of Hom_A(M, N): an A-linear map given
/// by one matrix per vertex, acting on row vectors.
///
/// Instances come from Module.hom (a basis of the hom space) or Module.morphism
/// (a checked construction); every Morphism satisfies all commuting squares.
#[pyclass(name = "Morphism", module = "auslander")]
struct PyMorphism {
    inner: hom::Morphism,
}

#[pymethods]
impl PyMorphism {
    /// The vertex matrices as canonical integers in 0..p: maps[v] is the
    /// dims_source[v] x dims_target[v] matrix at vertex v, one list per row, in
    /// the same shape `algebra.module` and `Module.morphism` accept.
    #[getter]
    fn maps(&self) -> Vec<Vec<Vec<u64>>> {
        let n = self.inner.source().algebra().quiver().num_vertices();
        (0..n).map(|v| self.inner.map_at(v).entries_u64()).collect()
    }

    /// Whether every vertex matrix is square and invertible, i.e. the morphism
    /// is an isomorphism.
    #[pyo3(text_signature = "($self)")]
    fn is_isomorphism(&self) -> bool {
        self.inner.is_isomorphism()
    }

    fn __repr__(&self) -> String {
        format!(
            "Morphism(source_dims={:?}, target_dims={:?})",
            self.inner.source().dim_vector(),
            self.inner.target().dim_vector()
        )
    }
}

/// How a computed resolution prefix ended: FINITE (reached zero) or CUT (step
/// budget ran out with the next syzygy nonzero).
#[pyclass(name = "ResolutionKind", module = "auslander", frozen, eq)]
#[derive(Clone, Copy, PartialEq)]
enum PyResolutionKind {
    #[pyo3(name = "FINITE")]
    Finite,
    #[pyo3(name = "CUT")]
    Cut,
}

/// How a resolution prefix ended, never overclaiming: kind FINITE with at None
/// means the resolution reached zero; kind CUT with at = n means exactly n
/// differentials were computed and the (n+1)-st syzygy is nonzero, with nothing
/// claimed beyond it. The invariant kind == FINITE iff at is None is enforced
/// at construction, and instances are immutable.
#[pyclass(name = "ResolutionStatus", module = "auslander", frozen, eq)]
#[derive(PartialEq)]
struct PyResolutionStatus {
    end: ResolutionEnd,
}

#[pymethods]
impl PyResolutionStatus {
    /// ResolutionStatus(kind, at=None); raises ValueError unless FINITE comes
    /// with at=None and CUT with an integer at.
    #[new]
    #[pyo3(signature = (kind, at = None), text_signature = "(kind, at=None)")]
    fn new(kind: PyResolutionKind, at: Option<usize>) -> PyResult<Self> {
        let end = match (kind, at) {
            (PyResolutionKind::Finite, None) => ResolutionEnd::Finite,
            (PyResolutionKind::Cut, Some(at)) => ResolutionEnd::Cut { at },
            (PyResolutionKind::Finite, Some(_)) => {
                return Err(PyValueError::new_err(
                    "ResolutionStatus: FINITE takes at=None",
                ));
            }
            (PyResolutionKind::Cut, None) => {
                return Err(PyValueError::new_err(
                    "ResolutionStatus: CUT needs an integer at",
                ));
            }
        };
        Ok(PyResolutionStatus { end })
    }

    /// ResolutionKind.FINITE or ResolutionKind.CUT.
    #[getter]
    fn kind(&self) -> PyResolutionKind {
        match self.end {
            ResolutionEnd::Finite => PyResolutionKind::Finite,
            ResolutionEnd::Cut { .. } => PyResolutionKind::Cut,
        }
    }

    /// The number of computed differentials for CUT; None for FINITE.
    #[getter]
    fn at(&self) -> Option<usize> {
        match self.end {
            ResolutionEnd::Finite => None,
            ResolutionEnd::Cut { at } => Some(at),
        }
    }

    fn __repr__(&self) -> String {
        match self.end {
            ResolutionEnd::Finite => "ResolutionStatus(ResolutionKind.FINITE)".to_string(),
            ResolutionEnd::Cut { at } => {
                format!("ResolutionStatus(ResolutionKind.CUT, at={at})")
            }
        }
    }
}

/// A minimal projective resolution prefix ... -> P_1 -> P_0 -> M -> 0.
///
/// `terms_dims[k]` is the dimension vector of P_k. `status` says how the computed
/// prefix ended and never overclaims; see ResolutionStatus.
#[pyclass(name = "Resolution", module = "auslander")]
struct PyResolution {
    module: Module,
    terms_dims: Vec<Vec<usize>>,
    end: ResolutionEnd,
}

#[pymethods]
impl PyResolution {
    /// Dimension vectors of the terms: terms_dims[k] is the dim vector of P_k.
    #[getter]
    fn terms_dims(&self) -> Vec<Vec<usize>> {
        self.terms_dims.clone()
    }

    /// How the prefix ended, as an immutable ResolutionStatus: kind FINITE (the
    /// resolution reached zero, so pd M = len(terms_dims) - 1 for nonzero M) or
    /// kind CUT with at = n (exactly n differentials computed, the (n+1)-st
    /// syzygy nonzero).
    #[getter]
    fn status(&self) -> PyResolutionStatus {
        PyResolutionStatus { end: self.end }
    }

    /// The projective dimension of the resolved module, decided up to `bound`
    /// differentials: Exact(n) with n <= bound, or AtLeast(bound + 1): the
    /// resolution is minimal, so the lower bound is genuine.
    #[pyo3(text_signature = "($self, bound)")]
    fn pd(&self, bound: usize) -> PyBounded {
        PyBounded {
            inner: projective_dimension(&self.module, bound),
        }
    }

    fn __repr__(&self) -> String {
        let status = match self.end {
            ResolutionEnd::Finite => "finite".to_string(),
            ResolutionEnd::Cut { at } => format!("('cut', {at})"),
        };
        format!(
            "Resolution(terms={}, status={status})",
            self.terms_dims.len()
        )
    }
}

/// A homological invariant known exactly or bounded from below.
///
/// Exactly one of `exact` and `at_least` is set. AtLeast(n) asserts only that the
/// true value is >= n; it does not claim the value finite or infinite. There is no
/// "None means infinite" convention anywhere in this package.
#[pyclass(name = "Bounded", module = "auslander")]
struct PyBounded {
    inner: Bounded<usize>,
}

#[pymethods]
impl PyBounded {
    /// The exact value, or None when only a lower bound is known.
    #[getter]
    fn exact(&self) -> Option<usize> {
        match self.inner {
            Bounded::Exact(n) => Some(n),
            Bounded::AtLeast(_) => None,
        }
    }

    /// The genuine lower bound, or None when the value is known exactly.
    #[getter]
    fn at_least(&self) -> Option<usize> {
        match self.inner {
            Bounded::Exact(_) => None,
            Bounded::AtLeast(n) => Some(n),
        }
    }

    fn __repr__(&self) -> String {
        match self.inner {
            Bounded::Exact(n) => format!("Exact({n})"),
            Bounded::AtLeast(n) => format!("AtLeast({n})"),
        }
    }

    fn __eq__(&self, other: &Bound<'_, PyAny>) -> bool {
        other
            .extract::<PyRef<'_, PyBounded>>()
            .is_ok_and(|o| o.inner == self.inner)
    }
}

/// The global dimension of the algebra, decided up to `bound` differentials:
/// gldim A = max_v pd S_v. Returns Exact when every simple resolves within the
/// bound, AtLeast(bound + 1) otherwise.
#[pyfunction]
#[pyo3(text_signature = "(algebra, field, bound)")]
fn global_dimension(algebra: &PyAlgebra, field: &PyPrimeField, bound: usize) -> PyBounded {
    PyBounded {
        inner: ext::global_dimension(&algebra.inner, field.inner, bound),
    }
}

/// Finite-dimensional basic algebras kQ/I over a checked prime field, where I is
/// an admissible monomial ideal, and their finite-dimensional right modules.
/// Convention: paths compose left to right, and modules are right modules whose
/// arrow matrices act on row vectors.
#[pymodule(name = "auslander")]
fn auslander_py(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyPrimeField>()?;
    m.add_class::<PyQuiver>()?;
    m.add_class::<PyAlgebra>()?;
    m.add_class::<PyRightModule>()?;
    m.add_class::<PyMorphism>()?;
    m.add_class::<PyResolutionKind>()?;
    m.add_class::<PyResolutionStatus>()?;
    m.add_class::<PyResolution>()?;
    m.add_class::<PyBounded>()?;
    m.add_function(wrap_pyfunction!(global_dimension, m)?)?;
    Ok(())
}
