from typing import TYPE_CHECKING

from ._core import _CoreValue, Module

if TYPE_CHECKING:
    from ._algebra import Algebra
    from ._catalog import IndecomposableCatalog


class CatalogAtlasLimits:
    def __init__(
        self,
        max_pairs: int | None = ...,
        max_ext_cells: int | None = ...,
        max_resolution_terms: int | None = ...,
        max_materialized_summands: int | None = ...,
        max_materialized_cells: int | None = ...,
    ) -> None: ...
    @property
    def max_pairs(self) -> int: ...
    @property
    def max_ext_cells(self) -> int: ...
    @property
    def max_resolution_terms(self) -> int: ...
    @property
    def max_materialized_summands(self) -> int: ...
    @property
    def max_materialized_cells(self) -> int: ...


class MultiplicityLimits:
    def __init__(
        self,
        max_solutions: int | None = ...,
        max_nodes: int | None = ...,
    ) -> None: ...
    @property
    def max_solutions(self) -> int: ...
    @property
    def max_nodes(self) -> int: ...


class CatalogAtlasWork:
    @property
    def pairs(self) -> int: ...
    @property
    def ext_cells(self) -> int: ...
    @property
    def resolutions(self) -> int: ...
    @property
    def resolution_terms(self) -> int: ...
    @property
    def ext_tables(self) -> int: ...


class CatalogExtRow:
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...
    @property
    def vanishes(self) -> bool: ...


class CatalogExtTable:
    @property
    def catalog_len(self) -> int: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def rows(self) -> list[CatalogExtRow]: ...
    def row(self, source: int, target: int) -> CatalogExtRow | None: ...
    def dimensions(self, source: int, target: int) -> list[int] | None: ...
    def dim(self, source: int, target: int, degree: int) -> int | None: ...
    def __len__(self) -> int: ...


class MultiplicityCutReason:
    @property
    def kind(self) -> str: ...
    @property
    def limit(self) -> int: ...


class MultiplicityComplete(_CoreValue):
    @property
    def catalog(self) -> IndecomposableCatalog: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def target_dimensions(self) -> list[int]: ...
    @property
    def solutions(self) -> list[list[int]]: ...
    @property
    def limits(self) -> MultiplicityLimits: ...
    @property
    def nodes_visited(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def verification(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> list[int]: ...


class MultiplicityCut(_CoreValue):
    @property
    def catalog(self) -> IndecomposableCatalog: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def target_dimensions(self) -> list[int]: ...
    @property
    def solutions(self) -> list[list[int]]: ...
    @property
    def limits(self) -> MultiplicityLimits: ...
    @property
    def reason(self) -> MultiplicityCutReason: ...
    @property
    def coverage(self) -> int: ...
    @property
    def nodes_visited(self) -> int: ...
    @property
    def limit(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def verification(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> list[int]: ...


class MultiplicityResult(_CoreValue):
    @property
    def catalog(self) -> IndecomposableCatalog: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def target_dimensions(self) -> list[int]: ...
    @property
    def solutions(self) -> list[list[int]]: ...
    @property
    def status(self) -> str: ...
    @property
    def verification(self) -> str: ...
    @property
    def is_complete(self) -> bool: ...
    @property
    def is_cut(self) -> bool: ...
    @property
    def complete(self) -> MultiplicityComplete | None: ...
    @property
    def cut(self) -> MultiplicityCut | None: ...
    @property
    def cut_reason(self) -> MultiplicityCutReason | None: ...
    @property
    def nodes_visited(self) -> int: ...
    @property
    def coverage(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> list[int]: ...


class CatalogAtlasArtifactParseLimits:
    def __init__(
        self,
        max_input_bytes: int | None = ...,
        max_certificate_bytes: int | None = ...,
        max_catalog_entries: int | None = ...,
        max_dimensions: int | None = ...,
        max_dimension: int | None = ...,
        max_ext_rows: int | None = ...,
        max_ext_degrees: int | None = ...,
        max_result_rows: int | None = ...,
        max_multiplicity_values: int | None = ...,
        max_numeric_values: int | None = ...,
        max_array_elements: int | None = ...,
        max_integer_digits: int | None = ...,
        max_string_bytes: int | None = ...,
    ) -> None: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_certificate_bytes(self) -> int: ...
    @property
    def max_catalog_entries(self) -> int: ...
    @property
    def max_dimensions(self) -> int: ...
    @property
    def max_dimension(self) -> int: ...
    @property
    def max_ext_rows(self) -> int: ...
    @property
    def max_ext_degrees(self) -> int: ...
    @property
    def max_result_rows(self) -> int: ...
    @property
    def max_multiplicity_values(self) -> int: ...
    @property
    def max_numeric_values(self) -> int: ...
    @property
    def max_array_elements(self) -> int: ...
    @property
    def max_integer_digits(self) -> int: ...
    @property
    def max_string_bytes(self) -> int: ...


class CatalogAtlasArtifactVerifyLimits:
    def __init__(
        self,
        parse: CatalogAtlasArtifactParseLimits | None = ...,
        max_vertices: int | None = ...,
        max_arrows: int | None = ...,
        max_algebra_dimension: int | None = ...,
        max_catalog_entries: int | None = ...,
        max_dimension: int | None = ...,
        max_degree: int | None = ...,
        max_pairs: int | None = ...,
        max_ext_cells: int | None = ...,
        max_resolution_terms: int | None = ...,
        max_result_rows: int | None = ...,
        max_multiplicity: int | None = ...,
        max_nodes: int | None = ...,
        max_materialized_summands: int | None = ...,
        max_materialized_cells: int | None = ...,
        max_entry_total_dimension: int | None = ...,
        max_generic_ext_cells: int | None = ...,
    ) -> None: ...
    @property
    def parse(self) -> CatalogAtlasArtifactParseLimits: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_certificate_bytes(self) -> int: ...
    @property
    def max_dimensions(self) -> int: ...
    @property
    def max_ext_rows(self) -> int: ...
    @property
    def max_ext_degrees(self) -> int: ...
    @property
    def max_multiplicity_values(self) -> int: ...
    @property
    def max_numeric_values(self) -> int: ...
    @property
    def max_array_elements(self) -> int: ...
    @property
    def max_integer_digits(self) -> int: ...
    @property
    def max_string_bytes(self) -> int: ...
    @property
    def max_vertices(self) -> int: ...
    @property
    def max_arrows(self) -> int: ...
    @property
    def max_algebra_dimension(self) -> int: ...
    @property
    def max_catalog_entries(self) -> int: ...
    @property
    def max_dimension(self) -> int: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def max_pairs(self) -> int: ...
    @property
    def max_ext_cells(self) -> int: ...
    @property
    def max_resolution_terms(self) -> int: ...
    @property
    def max_result_rows(self) -> int: ...
    @property
    def max_multiplicity(self) -> int: ...
    @property
    def max_nodes(self) -> int: ...
    @property
    def max_materialized_summands(self) -> int: ...
    @property
    def max_materialized_cells(self) -> int: ...
    @property
    def max_entry_total_dimension(self) -> int: ...
    @property
    def max_generic_ext_cells(self) -> int: ...


class CatalogAtlas(_CoreValue):
    @property
    def catalog(self) -> IndecomposableCatalog: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def limits(self) -> CatalogAtlasLimits: ...
    @property
    def work(self) -> CatalogAtlasWork: ...
    @property
    def ext_table(self) -> CatalogExtTable: ...
    @property
    def pairs(self) -> list[CatalogExtRow]: ...
    def ext_dimensions(self, source: int, target: int) -> list[int] | None: ...
    def ext_dim(self, source: int, target: int, degree: int) -> int | None: ...
    @property
    def verification(self) -> str: ...
    @property
    def status(self) -> str: ...
    def verify(self) -> bool: ...
    def enumerate(
        self,
        dimensions: list[int],
        limits: MultiplicityLimits | None = ...,
    ) -> MultiplicityResult: ...
    def ext_scores(
        self,
        left: list[int],
        right: list[int],
        first: int = 0,
        last: int | None = None,
    ) -> list[int]: ...
    def self_ext_scores(
        self,
        multiplicities: list[int],
        first: int = 0,
        last: int | None = None,
    ) -> list[int]: ...
    def ext_vanishes(
        self,
        left: list[int],
        right: list[int],
        first: int = 0,
        last: int | None = None,
    ) -> bool: ...
    def self_ext_vanishes(
        self,
        multiplicities: list[int],
        first: int = 0,
        last: int | None = None,
    ) -> bool: ...
    def materialize(self, multiplicities: list[int]) -> Module: ...
    def export(
        self,
        dimensions: list[int],
        limits: MultiplicityLimits | None = ...,
    ) -> CatalogAtlasArtifact: ...
    def __len__(self) -> int: ...


class CatalogAtlasArtifactExtRow:
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...


class CatalogAtlasArtifactResultRow:
    @property
    def multiplicities(self) -> list[int]: ...
    @property
    def self_ext(self) -> list[int]: ...


class CatalogAtlasArtifactStatus:
    @property
    def kind(self) -> str: ...
    @property
    def is_complete(self) -> bool: ...
    @property
    def is_cut(self) -> bool: ...
    @property
    def coverage(self) -> int | None: ...
    @property
    def cut_reason(self) -> MultiplicityCutReason | None: ...
    @property
    def nodes_visited(self) -> int | None: ...


class CatalogAtlasArtifact(_CoreValue):
    def __init__(
        self,
        text: str,
        limits: CatalogAtlasArtifactVerifyLimits | None = ...,
    ) -> None: ...
    @property
    def schema(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def engine(self) -> str: ...
    @property
    def certificate_json(self) -> str: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def catalog_ids(self) -> list[int]: ...
    @property
    def target_dimensions(self) -> list[int]: ...
    @property
    def catalog_len(self) -> int: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def atlas_limits(self) -> CatalogAtlasLimits: ...
    @property
    def multiplicity_limits(self) -> MultiplicityLimits: ...
    @property
    def work(self) -> CatalogAtlasWork: ...
    @property
    def ext_rows(self) -> list[CatalogAtlasArtifactExtRow]: ...
    @property
    def result_rows(self) -> list[CatalogAtlasArtifactResultRow]: ...
    @property
    def status(self) -> str: ...
    @property
    def enumeration_status(self) -> CatalogAtlasArtifactStatus: ...
    @property
    def cut_reason(self) -> MultiplicityCutReason | None: ...
    @property
    def verification(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def has_valid_fingerprint(self) -> bool: ...
    def verify(
        self,
        limits: CatalogAtlasArtifactVerifyLimits | None = ...,
    ) -> VerifiedCatalogAtlasArtifact: ...
    @property
    def canonical_json(self) -> str: ...
    def __len__(self) -> int: ...


class VerifiedCatalogAtlasArtifact(_CoreValue):
    @property
    def artifact(self) -> CatalogAtlasArtifact: ...
    @property
    def algebra(self) -> Algebra: ...
    @property
    def catalog(self) -> IndecomposableCatalog: ...
    @property
    def atlas(self) -> CatalogAtlas: ...
    @property
    def certificate_json(self) -> str: ...
    @property
    def field(self) -> int: ...
    @property
    def provenance(self) -> str: ...
    @property
    def target_dimensions(self) -> list[int]: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def enumeration_status(self) -> CatalogAtlasArtifactStatus: ...
    @property
    def cut_reason(self) -> MultiplicityCutReason | None: ...
    @property
    def catalog_ids(self) -> list[int]: ...
    @property
    def catalog_len(self) -> int: ...
    @property
    def atlas_limits(self) -> CatalogAtlasLimits: ...
    @property
    def multiplicity_limits(self) -> MultiplicityLimits: ...
    @property
    def work(self) -> CatalogAtlasWork: ...
    @property
    def ext_rows(self) -> list[CatalogAtlasArtifactExtRow]: ...
    @property
    def result_rows(self) -> list[CatalogAtlasArtifactResultRow]: ...
    @property
    def verification(self) -> str: ...
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def verify(self) -> bool: ...


def verify_catalog_atlas_artifact(
    text: str,
    limits: CatalogAtlasArtifactVerifyLimits | None = ...,
) -> VerifiedCatalogAtlasArtifact: ...
