from typing import TYPE_CHECKING

from ._core import ArQuiver, Decomposition, Morphism, SupportTauTiltingPair, _CoreValue, Module, PrimeField

if TYPE_CHECKING:
    from ._algebra import Algebra
    from ._atlas import CatalogAtlas, CatalogAtlasLimits


class IndecomposableCatalog(_CoreValue):
    @staticmethod
    def auto(
        algebra: Algebra, field: PrimeField | None = ...
    ) -> IndecomposableCatalog: ...

    @staticmethod
    def dynkin(
        algebra: Algebra, field: PrimeField | None = ...
    ) -> IndecomposableCatalog: ...

    @staticmethod
    def nakayama(
        algebra: Algebra, field: PrimeField | None = ...
    ) -> IndecomposableCatalog: ...

    @staticmethod
    def gentle_tree(
        algebra: Algebra, field: PrimeField | None = ...
    ) -> IndecomposableCatalog: ...

    def higher_orthogonality(
        self,
        chosen: list[int],
        max_degree: int,
        limits: HigherOrthogonalityLimits | None = ...,
    ) -> HigherOrthogonality: ...
    def ar_quiver(self) -> ArQuiver: ...
    def coordinates(
        self,
        module: Module,
        limits: CatalogCoordinateLimits | None = ...,
    ) -> CatalogCoordinates | CatalogCoordinateUnknown | CatalogCoordinateCut: ...
    @property
    def entries(self) -> list[Module]: ...
    @property
    def provenance(self) -> str: ...
    @property
    def field(self) -> PrimeField: ...
    def atlas(
        self,
        max_degree: int,
        limits: CatalogAtlasLimits | None = ...,
    ) -> CatalogAtlas: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Module: ...


def catalog(
    algebra: Algebra, field: PrimeField | None = ...
) -> IndecomposableCatalog: ...


class HigherOrthogonalityLimits:
    def __init__(
        self,
        max_pairs: int | None = ...,
        max_ext_cells: int | None = ...,
    ) -> None: ...
    @property
    def max_pairs(self) -> int: ...
    @property
    def max_ext_cells(self) -> int: ...


class HigherExtPair:
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...
    @property
    def ext_dimensions(self) -> list[int]: ...
    @property
    def vanishes(self) -> bool: ...


class HigherOrthogonalityWork:
    @property
    def resolutions(self) -> int: ...
    @property
    def ext_tables(self) -> int: ...


class HigherOrthogonality(_CoreValue):
    @staticmethod
    def compute(
        catalog: IndecomposableCatalog,
        chosen: list[int],
        max_degree: int,
        limits: HigherOrthogonalityLimits | None = ...,
    ) -> HigherOrthogonality: ...
    @property
    def provenance(self) -> str: ...
    @property
    def chosen(self) -> list[int]: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def pairs(self) -> list[HigherExtPair]: ...
    @property
    def left(self) -> list[int]: ...
    @property
    def right(self) -> list[int]: ...
    @property
    def is_rigid(self) -> bool: ...
    @property
    def is_two_sided_maximal(self) -> bool: ...
    @property
    def work(self) -> HigherOrthogonalityWork: ...
    def verify(self, catalog: IndecomposableCatalog) -> bool: ...


def higher_orthogonality(
    catalog: IndecomposableCatalog,
    chosen: list[int],
    max_degree: int,
    limits: HigherOrthogonalityLimits | None = ...,
) -> HigherOrthogonality: ...


class CatalogCoordinateLimits:
    def __init__(self, max_work_units: int | None = ...) -> None: ...
    @property
    def max_work_units(self) -> int: ...


class CatalogCoordinateMatch:
    @property
    def summand(self) -> int: ...
    @property
    def catalog_entry(self) -> int: ...
    @property
    def witness(self) -> Morphism: ...


class CatalogCoordinateProgress(_CoreValue):
    @property
    def decomposition(self) -> Decomposition: ...
    @property
    def multiplicities(self) -> list[int]: ...
    @property
    def matches(self) -> list[CatalogCoordinateMatch]: ...
    @property
    def work_units(self) -> int: ...
    @property
    def verification(self) -> str: ...
    def verify(self, catalog: IndecomposableCatalog, module: Module) -> bool: ...
    def __len__(self) -> int: ...


class CatalogCoordinates(_CoreValue):
    @property
    def algebra(self) -> Algebra: ...
    @property
    def field(self) -> PrimeField: ...
    @property
    def provenance(self) -> str: ...
    @property
    def multiplicities(self) -> list[int]: ...
    @property
    def decomposition(self) -> Decomposition: ...
    @property
    def matches(self) -> list[CatalogCoordinateMatch]: ...
    @property
    def work_units(self) -> int: ...
    @property
    def progress(self) -> CatalogCoordinateProgress: ...
    @property
    def status(self) -> str: ...
    @property
    def is_exact(self) -> bool: ...
    @property
    def verification(self) -> str: ...
    def verify(self, catalog: IndecomposableCatalog, module: Module) -> bool: ...
    def __len__(self) -> int: ...


class CatalogCoordinateUnknownReason:
    @property
    def kind(self) -> str: ...
    @property
    def summand(self) -> int: ...
    @property
    def catalog_entry(self) -> int | None: ...
    @property
    def attempts(self) -> int | None: ...
    @property
    def detail(self) -> str | None: ...


class CatalogCoordinateUnknown(_CoreValue):
    @property
    def progress(self) -> CatalogCoordinateProgress: ...
    @property
    def reason(self) -> CatalogCoordinateUnknownReason: ...
    @property
    def kind(self) -> str: ...
    @property
    def summand(self) -> int: ...
    @property
    def catalog_entry(self) -> int | None: ...
    @property
    def attempts(self) -> int | None: ...
    @property
    def detail(self) -> str | None: ...
    @property
    def decomposition(self) -> Decomposition: ...
    @property
    def multiplicities(self) -> list[int]: ...
    @property
    def matches(self) -> list[CatalogCoordinateMatch]: ...
    @property
    def work_units(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def is_exact(self) -> bool: ...
    @property
    def verification(self) -> str: ...
    def verify(self, catalog: IndecomposableCatalog, module: Module) -> bool: ...


class CatalogCoordinateCutReason:
    @property
    def kind(self) -> str: ...
    @property
    def limit(self) -> int: ...


class CatalogCoordinateCut(_CoreValue):
    @property
    def progress(self) -> CatalogCoordinateProgress: ...
    @property
    def reason(self) -> CatalogCoordinateCutReason: ...
    @property
    def kind(self) -> str: ...
    @property
    def limit(self) -> int: ...
    @property
    def decomposition(self) -> Decomposition: ...
    @property
    def multiplicities(self) -> list[int]: ...
    @property
    def matches(self) -> list[CatalogCoordinateMatch]: ...
    @property
    def work_units(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def is_exact(self) -> bool: ...
    @property
    def verification(self) -> str: ...
    def verify(self, catalog: IndecomposableCatalog, module: Module) -> bool: ...


class CatalogEnumeration(_CoreValue):
    def pairs(self) -> list[SupportTauTiltingPair]: ...
    @property
    def provenance(self) -> str: ...
    @property
    def catalog_len(self) -> int: ...
    @property
    def nodes_visited(self) -> int: ...
    def histogram(self) -> list[int]: ...
    def verify(self) -> bool: ...
    def __len__(self) -> int: ...
