from typing import Any, ClassVar
from ._algebra import Algebra as Algebra
from ._catalog import *
from ._atlas import *
class _CoreValue:
    def __getattr__(self, name: str) -> Any: ...
class PrimeField(_CoreValue):
    def __init__(self, p: int) -> None: ...
    @property
    def p(self) -> int: ...
class Quiver(_CoreValue):
    def __init__(self, num_vertices: int, arrows: list[tuple[int, int]]) -> None: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_arrows(self) -> int: ...
    @property
    def arrows(self) -> list[tuple[int, int]]: ...
class Module(_CoreValue):
    @property
    def dims(self) -> list[int]: ...
    maps: list[list[list[int]]]
    total_dim: int
    sparse_maps: list[list[tuple[int, int, int]]]
    def hom(self, other: Module) -> list[Morphism]: ...
    def stable_hom(self, other: Module) -> StableHomSpace: ...
    def stable_hom_dim(self, other: Module) -> int: ...
    def morphism(self, target: Module, maps: list[list[list[int]]]) -> Morphism: ...
    def hom_dim(self, other: Module) -> int: ...
    def ext_dim(self, other: Module, k: int) -> int: ...
    def ext_table(self, other: Module, max_k: int) -> list[int]: ...
    def radical_series_dims(self) -> list[list[int]]: ...
    def loewy_length(self) -> int: ...
    def top_dims(self) -> list[int]: ...
    def socle_dims(self) -> list[int]: ...
    def projective_cover(self) -> tuple[Module, Morphism]: ...
    def resolve(self, steps: int) -> Resolution: ...
    def syzygy(self, degree: int = ...) -> Syzygy: ...
    def cosyzygy(self, degree: int = ...) -> Cosyzygy: ...
    def injective_envelope(self) -> tuple[Module, Morphism]: ...
    def coresolve(self, steps: int) -> InjectiveCoresolution: ...
    def injective_dimension(self, bound: int) -> Bounded: ...
    def decompose(self) -> Decomposition: ...
    def krull_schmidt(self) -> KrullSchmidtResult: ...
    def tau(self) -> Module: ...
    def ext_space(self, other: Module, degree: int) -> ExtSpace: ...
    def ext_algebra(self, bound: int) -> ExtAlgebra | IncompleteExtAlgebra: ...
    def almost_split(self) -> AlmostSplitOutcome | AlmostSplitSequence: ...
    def category_radical(self, other: Module) -> CategoryRadical: ...
    def is_isomorphic(self, other: Module) -> IsoResult: ...
    def tau_rigidity(self) -> TauRigidity: ...
class Morphism(_CoreValue):
    source: Module
    target: Module
    @property
    def maps(self) -> list[list[list[int]]]: ...
    @property
    def sparse_maps(self) -> list[list[tuple[int, int, int]]]: ...
    def map_at(self, v: int) -> list[list[int]]: ...
    def is_isomorphism(self) -> bool: ...
    is_zero: bool
    def then(self, other: Morphism) -> Morphism: ...
class StableHomSpace(_CoreValue):
    @property
    def source(self) -> Module: ...
    @property
    def target(self) -> Module: ...
    @property
    def dim(self) -> int: ...
    @property
    def projective_factor_dim(self) -> int: ...
    @property
    def projective_factor_basis(self) -> list[Morphism]: ...
    @property
    def basis(self) -> list[Morphism]: ...
    def is_projective_factor(self, morphism: Morphism) -> bool: ...
    def representative(self, coordinates: list[int]) -> Morphism: ...
    def reduce(self, morphism: Morphism) -> tuple[list[int], Morphism]: ...
class HomologicalBatchLimits:
    def __init__(self, max_pairs: int | None = ..., max_ext_cells: int | None = ...) -> None: ...
    @property
    def max_pairs(self) -> int: ...
    @property
    def max_ext_cells(self) -> int: ...
class HomologicalPair:
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def hom_dim(self) -> int: ...
    @property
    def stable_hom_dim(self) -> int: ...
    @property
    def ext_dimensions(self) -> list[int]: ...
class HomologicalBatch(_CoreValue):
    def __init__(self, modules: list[Module], max_degree: int, pairs: list[tuple[int, int]] | None = ..., limits: HomologicalBatchLimits | None = ...) -> None: ...
    @classmethod
    def all_pairs(cls, modules: list[Module], max_degree: int, limits: HomologicalBatchLimits | None = ...) -> HomologicalBatch: ...
    @property
    def modules(self) -> list[Module]: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def selected_pairs(self) -> list[tuple[int, int]]: ...
    @property
    def pairs(self) -> list[HomologicalPair]: ...
    @property
    def work(self) -> HomologicalBatchWork: ...
    def resolution(self, source: int) -> Resolution | None: ...
    def stable_hom(self, pair: int) -> StableHomSpace: ...
class HomologicalBatchWork:
    @property
    def resolutions(self) -> int: ...
    @property
    def target_covers(self) -> int: ...
    @property
    def hom_spaces(self) -> int: ...
    @property
    def projective_factor_spaces(self) -> int: ...
    @property
    def ext_tables(self) -> int: ...
class HomologicalStreamBudget:
    def __init__(self, max_sources: int | None = ..., max_work_units: int | None = ...) -> None: ...
    @property
    def max_sources(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class HomologicalStreamConfig:
    def __init__(self, max_live_sources: int | None = ..., max_pairs: int | None = ..., max_ext_cells: int | None = ..., max_sources: int | None = ..., max_work_units: int | None = ...) -> None: ...
    @property
    def max_live_sources(self) -> int: ...
    @property
    def max_pairs(self) -> int: ...
    @property
    def max_ext_cells(self) -> int: ...
    @property
    def max_sources(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class HomologicalStreamVerifyLimits:
    def __init__(self, census: CensusVerifyLimits | None = ..., max_input_bytes: int | None = ..., max_census_bytes: int | None = ..., max_rows: int | None = ..., max_ext_dimensions: int | None = ..., max_numeric_values: int | None = ..., max_array_elements: int | None = ..., max_integer_digits: int | None = ..., max_string_bytes: int | None = ..., max_representatives: int | None = ..., max_degree: int | None = ..., max_work_units: int | None = ...) -> None: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_census_bytes(self) -> int: ...
    @property
    def max_rows(self) -> int: ...
    @property
    def max_ext_dimensions(self) -> int: ...
    @property
    def max_numeric_values(self) -> int: ...
    @property
    def max_array_elements(self) -> int: ...
    @property
    def max_integer_digits(self) -> int: ...
    @property
    def max_string_bytes(self) -> int: ...
    @property
    def census(self) -> CensusVerifyLimits: ...
    @property
    def max_representatives(self) -> int: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class HomologicalStreamCutReason:
    @property
    def kind(self) -> str: ...
    @property
    def limit(self) -> int | None: ...
class HomologicalStreamRow:
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def hom_dim(self) -> int: ...
    @property
    def stable_hom_dim(self) -> int: ...
    @property
    def ext_dimensions(self) -> list[int]: ...
    @property
    def resolution_status(self) -> str: ...
    @property
    def resolution_cut_at(self) -> int | None: ...
class HomologicalStreamWork:
    @property
    def chunks(self) -> int: ...
    @property
    def sources(self) -> int: ...
    @property
    def resolutions(self) -> int: ...
    @property
    def target_covers(self) -> int: ...
    @property
    def hom_spaces(self) -> int: ...
    @property
    def projective_factor_spaces(self) -> int: ...
    @property
    def ext_tables(self) -> int: ...
    @property
    def peak_live_sources(self) -> int: ...
class HomologicalCheckpoint:
    def __init__(self, text: str, limits: HomologicalStreamVerifyLimits | None = ...) -> None: ...
    @classmethod
    def from_json(cls, text: str, limits: HomologicalStreamVerifyLimits | None = ...) -> HomologicalCheckpoint: ...
    @property
    def census_json(self) -> str: ...
    @property
    def census_fingerprint(self) -> str: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def config(self) -> HomologicalStreamConfig: ...
    @property
    def next_source(self) -> int: ...
    @property
    def rows(self) -> list[HomologicalStreamRow]: ...
    @property
    def row_count(self) -> int: ...
    @property
    def chunk_sizes(self) -> list[int]: ...
    @property
    def work(self) -> HomologicalStreamWork: ...
    @property
    def status(self) -> str: ...
    @property
    def cut_reason(self) -> HomologicalStreamCutReason | None: ...
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def verify(self, limits: HomologicalStreamVerifyLimits | None = ...) -> VerifiedHomologicalCheckpoint: ...
class VerifiedHomologicalCheckpoint:
    @property
    def checkpoint(self) -> HomologicalCheckpoint: ...
    @property
    def status(self) -> str: ...
    @property
    def next_source(self) -> int: ...
    @property
    def chunk_sizes(self) -> list[int]: ...
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def resume(self, budget: HomologicalStreamBudget | None = ..., control: ComputationControl | None = ...) -> HomologicalCheckpointStream: ...
class HomologicalCheckpointStream:
    @property
    def checkpoint(self) -> HomologicalCheckpoint: ...
    def advance(self) -> HomologicalCheckpoint: ...
class SelfExtLocusVerifyLimits:
    def __init__(self, checkpoint: HomologicalStreamVerifyLimits | None = ..., max_input_bytes: int | None = ..., max_vanishing_indices: int | None = ..., max_integer_digits: int | None = ..., max_string_bytes: int | None = ..., max_representatives: int | None = ..., max_degree_span: int | None = ..., max_ext_spaces: int | None = ...) -> None: ...
    checkpoint: HomologicalStreamVerifyLimits
    max_input_bytes: int
    max_vanishing_indices: int
    max_integer_digits: int
    max_string_bytes: int
    max_representatives: int
    max_degree_span: int
    max_ext_spaces: int
class SelfExtLocusArtifact:
    def __init__(self, text: str, limits: SelfExtLocusVerifyLimits | None = ...) -> None: ...
    @classmethod
    def from_json(cls, text: str, limits: SelfExtLocusVerifyLimits | None = ...) -> SelfExtLocusArtifact: ...
    schema: str
    kind: str
    checkpoint: HomologicalCheckpoint
    first_degree: int
    last_degree: int
    vanishing_indices: list[int]
    vanishing_count: int
    canonical_json: str
    fingerprint: str
    def verify(self, limits: SelfExtLocusVerifyLimits | None = ...) -> VerifiedSelfExtLocusArtifact: ...
class VerifiedSelfExtLocusArtifact:
    artifact: SelfExtLocusArtifact
    checkpoint: VerifiedHomologicalCheckpoint
    canonical_json: str
    fingerprint: str
    first_degree: int
    last_degree: int
    vanishing_indices: list[int]
    vanishing_count: int
class CensusLimits:
    def __init__(self, max_candidates: int | None = ..., max_representatives: int | None = ..., max_assignments: int | None = ..., max_isomorphism_checks: int | None = ..., max_work_units: int | None = ..., *, retention: str | None = ...) -> None: ...
    @property
    def retention(self) -> str: ...
    @property
    def max_candidates(self) -> int: ...
    @property
    def max_representatives(self) -> int: ...
    @property
    def max_assignments(self) -> int: ...
    @property
    def max_isomorphism_checks(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class CensusVerifyLimits:
    def __init__(self, *, max_input_bytes: int | None = ..., max_certificate_bytes: int | None = ..., max_dimensions: int | None = ..., max_dimension: int | None = ..., max_representatives: int | None = ..., max_assignments: int | None = ..., max_coordinate_values: int | None = ..., max_witness_matrices: int | None = ..., max_witness_rows: int | None = ..., max_witness_columns: int | None = ..., max_witness_entries: int | None = ..., max_numeric_values: int | None = ..., max_array_elements: int | None = ..., max_integer_digits: int | None = ..., max_string_bytes: int | None = ..., max_vertices: int | None = ..., max_coordinates: int | None = ..., max_candidates: int | None = ..., max_isomorphism_checks: int | None = ..., max_work_units: int | None = ...) -> None: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_certificate_bytes(self) -> int: ...
    @property
    def max_dimensions(self) -> int: ...
    @property
    def max_dimension(self) -> int: ...
    @property
    def max_representatives(self) -> int: ...
    @property
    def max_assignments(self) -> int: ...
    @property
    def max_coordinate_values(self) -> int: ...
    @property
    def max_witness_matrices(self) -> int: ...
    @property
    def max_witness_rows(self) -> int: ...
    @property
    def max_witness_columns(self) -> int: ...
    @property
    def max_witness_entries(self) -> int: ...
    @property
    def max_numeric_values(self) -> int: ...
    @property
    def max_array_elements(self) -> int: ...
    @property
    def max_integer_digits(self) -> int: ...
    @property
    def max_string_bytes(self) -> int: ...
    @property
    def max_vertices(self) -> int: ...
    @property
    def max_coordinates(self) -> int: ...
    @property
    def max_candidates(self) -> int: ...
    @property
    def max_isomorphism_checks(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class CensusRepresentative:
    @property
    def cursor(self) -> int: ...
    @property
    def coordinates(self) -> list[int]: ...
class CensusAssignment:
    @property
    def cursor(self) -> int: ...
    @property
    def coordinates(self) -> list[int]: ...
    @property
    def representative(self) -> int: ...
    @property
    def witness(self) -> list[list[list[int]]]: ...
class CensusCutReason:
    @property
    def kind(self) -> str: ...
    @property
    def limit(self) -> int | None: ...
    @property
    def stage(self) -> str | None: ...
    @property
    def representative(self) -> int | None: ...
    @property
    def detail(self) -> str | None: ...
class CensusCheckpoint(_CoreValue):
    def __init__(self, text: str, limits: CensusVerifyLimits | None = ...) -> None: ...
    @classmethod
    def from_json(cls, text: str, limits: CensusVerifyLimits | None = ...) -> CensusCheckpoint: ...
    @classmethod
    def run(cls, algebra: Algebra, dimensions: list[int], field: PrimeField | None = ..., limits: CensusLimits | None = ..., control: ComputationControl | None = ...) -> CensusCheckpoint: ...
    @property
    def certificate_json(self) -> str: ...
    @property
    def field(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...
    @property
    def raw_space_size(self) -> int: ...
    @property
    def coordinate_count(self) -> int: ...
    @property
    def cursor(self) -> int: ...
    @property
    def limits(self) -> CensusLimits: ...
    @property
    def candidates(self) -> int: ...
    @property
    def accepted_modules(self) -> int: ...
    @property
    def rejected_candidates(self) -> int: ...
    @property
    def isomorphism_checks(self) -> int: ...
    @property
    def work_units(self) -> int: ...
    @property
    def counts(self) -> dict[str, int]: ...
    @property
    def representatives(self) -> list[CensusRepresentative]: ...
    @property
    def assignments(self) -> list[CensusAssignment]: ...
    @property
    def representative_count(self) -> int: ...
    @property
    def assignment_count(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def cut_reason(self) -> CensusCutReason | None: ...
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def verify(self, limits: CensusVerifyLimits | None = ...) -> VerifiedCensusCheckpoint: ...
class VerifiedCensusCheckpoint(_CoreValue):
    @property
    def certificate_json(self) -> str: ...
    @property
    def field(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...
    @property
    def raw_space_size(self) -> int: ...
    @property
    def coordinate_count(self) -> int: ...
    @property
    def cursor(self) -> int: ...
    @property
    def limits(self) -> CensusLimits: ...
    @property
    def candidates(self) -> int: ...
    @property
    def accepted_modules(self) -> int: ...
    @property
    def rejected_candidates(self) -> int: ...
    @property
    def isomorphism_checks(self) -> int: ...
    @property
    def work_units(self) -> int: ...
    @property
    def counts(self) -> dict[str, int]: ...
    @property
    def representatives(self) -> list[CensusRepresentative]: ...
    @property
    def assignments(self) -> list[CensusAssignment]: ...
    @property
    def representative_count(self) -> int: ...
    @property
    def assignment_count(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def cut_reason(self) -> CensusCutReason | None: ...
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def resume(self, limits: CensusLimits | None = ..., control: ComputationControl | None = ...) -> CensusCheckpoint: ...
class IsoResult(_CoreValue): ...
class Certificate(_CoreValue): ...
class Decomposition(_CoreValue): ...
class KrullSchmidtResult(_CoreValue): ...
class CheckedComplex(_CoreValue): ...
class HomologyDimensions(_CoreValue): ...
class NonExactWitness(_CoreValue): ...
class ExactComplex(_CoreValue): ...
class ComputationControl:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...
    @property
    def stage(self) -> str: ...
    @property
    def completed_work(self) -> int: ...
    @property
    def reserved_work(self) -> int: ...
class ReplacementLimits(_CoreValue):
    def __init__(self, max_resolution_steps: int = ..., max_complex_terms: int = ..., max_total_dimension: int = ..., max_matrix_entries: int = ..., max_work_units: int = ...) -> None: ...
class PerfectReplacement(_CoreValue): ...
class IncompletePerfectReplacement(_CoreValue): ...
class DerivedHomLimits(_CoreValue):
    def __init__(self, replacement: ReplacementLimits | None = ..., max_degrees: int = ..., max_work_units: int = ...) -> None: ...
class DerivedHom(_CoreValue): ...
class IncompleteDerivedHom(_CoreValue): ...
class BoundedComplex(_CoreValue):
    def perfect_replacement(self, limits: ReplacementLimits | None = ..., control: ComputationControl | None = ...) -> PerfectReplacement | IncompletePerfectReplacement: ...
    def derived_hom(self, target: BoundedComplex, limits: DerivedHomLimits | None = ..., control: ComputationControl | None = ...) -> DerivedHom | IncompleteDerivedHom: ...
class ChainMap(_CoreValue): ...
class ChainHomotopy(_CoreValue): ...
class HomotopyHom(_CoreValue): ...
class HomotopyHomQuotient(_CoreValue): ...
class ChainHomQuotient(_CoreValue): ...
class ResolutionKind(_CoreValue):
    FINITE: ClassVar[ResolutionKind]
    CUT: ClassVar[ResolutionKind]
class ResolutionStatus(_CoreValue):
    def __init__(self, kind: ResolutionKind, at: int | None = ...) -> None: ...
    @property
    def kind(self) -> ResolutionKind: ...
    @property
    def at(self) -> int | None: ...
class Resolution(_CoreValue):
    terms: list[Module]
    terms_dims: list[list[int]]
    maps: list[Morphism]
    augmentation: Morphism
    status: ResolutionStatus
    projective_dimension: Bounded
    def pd(self, bound: int) -> Bounded: ...
class InjectiveCoresolution(_CoreValue):
    terms: list[Module]
    terms_dims: list[list[int]]
    maps: list[Morphism]
    coaugmentation: Morphism
    status: ResolutionStatus
class Syzygy(_CoreValue):
    @property
    def source(self) -> Module: ...
    @property
    def degree(self) -> int: ...
    @property
    def module(self) -> Module: ...
    resolution: Resolution | None
    def verify(self) -> bool: ...
class Cosyzygy(_CoreValue):
    @property
    def source(self) -> Module: ...
    @property
    def degree(self) -> int: ...
    @property
    def module(self) -> Module: ...
    coresolution: InjectiveCoresolution | None
    def verify(self) -> bool: ...
class Bounded(_CoreValue):
    exact: int | None
    at_least: int | None
class DiagramFamily(_CoreValue): ...
class DynkinType(_CoreValue): ...
class EuclideanType(_CoreValue): ...
class ExtSpace(_CoreValue): ...
class ExtClass(_CoreValue): ...
class ExtProductWitness(_CoreValue): ...
class ExtAlgebra(_CoreValue): ...
class IncompleteExtAlgebra(_CoreValue): ...
class ExtMultiplication(_CoreValue): ...
class ExtProductRecord(_CoreValue): ...
class SplitWitness(_CoreValue): ...
class NonSplitWitness(_CoreValue): ...
class ShortExactSequence(_CoreValue): ...
class AlmostSplitOutcome(_CoreValue): ...
class AlmostSplitSequence(_CoreValue): ...
class CategoryRadical(_CoreValue): ...
class ArVertex(_CoreValue): ...
class ArArrow(_CoreValue): ...
class ArQuiver(_CoreValue): ...
class TauRigidModule(_CoreValue): ...
class TauRigidity(_CoreValue): ...
class PairRejection(_CoreValue): ...
class SupportTauTiltingPair(_CoreValue): ...
class AlmostCompletePair(_CoreValue): ...
class FacWitness(_CoreValue): ...
class Mutation(_CoreValue): ...
class MutationGraphLimits(_CoreValue):
    def __init__(self, *, max_vertices: int | None = ..., max_directed_mutations: int | None = ..., max_work_units: int | None = ..., max_matrix_entries: int | None = ...) -> None: ...
    @property
    def max_vertices(self) -> int: ...
    @property
    def max_directed_mutations(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
    @property
    def max_matrix_entries(self) -> int: ...
class GraphBudgetDiagnostics(_CoreValue): ...
class CertificationBlocker(_CoreValue): ...
class ClosedSupportTauTiltingGraph(_CoreValue): ...
class IncompleteSupportTauTiltingGraph(_CoreValue): ...
class AddClosureWitness(_CoreValue): ...
class BarLimits(_CoreValue):
    def __init__(self, max_tensor_tuples: int, max_cochain_dim: int, max_matrix_entries: int, max_work_units: int) -> None: ...
    @property
    def max_tensor_tuples(self) -> int: ...
    @property
    def max_cochain_dim(self) -> int: ...
    @property
    def max_matrix_entries(self) -> int: ...
    @property
    def max_work_units(self) -> int: ...
class BarBudgetDiagnostics(_CoreValue): ...
class BarRunDiagnostics(_CoreValue): ...
class HochschildCohomology(_CoreValue): ...
class IncompleteHochschildCohomology(_CoreValue): ...
class HochschildDegree(_CoreValue): ...
class HochschildClass(_CoreValue): ...
class TiltingLimits(_CoreValue):
    def __init__(self, max_projective_dimension: int, max_generation_steps: int) -> None: ...
    @property
    def max_projective_dimension(self) -> int: ...
    @property
    def max_generation_steps(self) -> int: ...
class TargetLimits(_CoreValue):
    def __init__(self, max_endo_dimension: int = ..., max_radical_products: int = ..., max_paths: int = ..., max_relation_terms: int = ..., max_basis: int = ..., max_word_len: int = ..., max_steps: int = ..., max_origin_terms: int = ..., max_ambiguities: int = ...) -> None: ...
    @property
    def max_endo_dimension(self) -> int: ...
    @property
    def max_radical_products(self) -> int: ...
    @property
    def max_paths(self) -> int: ...
    @property
    def max_relation_terms(self) -> int: ...
    @property
    def max_basis(self) -> int: ...
    @property
    def max_word_len(self) -> int: ...
    @property
    def max_steps(self) -> int: ...
    @property
    def max_origin_terms(self) -> int: ...
    @property
    def max_ambiguities(self) -> int: ...
class TargetWork(_CoreValue): ...
class TargetPresentation(_CoreValue): ...
class UnsupportedTarget(_CoreValue): ...
class IncompleteTargetPresentation(_CoreValue): ...
class ClassicalTiltingResult(_CoreValue): ...
class ClassicalTiltingModule(_CoreValue): ...
class PositiveSelfExtension(_CoreValue): ...
class TiltingBlocker(_CoreValue): ...
class AddTComplex(_CoreValue): ...
class ProjectiveTargetComplex(_CoreValue): ...
class ChainIsomorphism(_CoreValue): ...
class StrictTransport(_CoreValue): ...
class GradedHomotopyEndomorphisms(_CoreValue): ...
class DegreeZeroEndIdentification(_CoreValue): ...
class DerivedTransport(_CoreValue):
    def forward(self, input: BoundedComplex, limits: ReplacementLimits | None = ..., control: ComputationControl | None = ...) -> DerivedTransportResult | IncompletePerfectReplacement: ...
    def reverse(self, input: BoundedComplex, limits: ReplacementLimits | None = ..., control: ComputationControl | None = ...) -> DerivedTransportResult | IncompletePerfectReplacement: ...
class DerivedTransportResult(_CoreValue): ...
class DerivedEquivalenceCertificate(_CoreValue):
    @property
    def automatic_transport(self) -> DerivedTransport: ...
class EquivalenceDiscoveryLimits(_CoreValue):
    def __init__(self, max_vertices: int = ..., max_directed_mutations: int = ..., max_total_terms: int = ..., max_matrix_entries: int = ..., max_work_units: int = ..., max_hom_spaces: int = ...) -> None: ...
class IncompleteEquivalenceGraph(_CoreValue):
    @property
    def vertex_count(self) -> int: ...
    @property
    def keys(self) -> list[str]: ...
    @property
    def edges(self) -> list[tuple[int, int, str, int]]: ...
    @property
    def blocked(self) -> list[tuple[int, str, int, str]]: ...
    @property
    def stop(self) -> str: ...
    @property
    def completed_mutations(self) -> int: ...
    @property
    def total_terms(self) -> int: ...
    @property
    def matrix_entries(self) -> int: ...
class VerifiedDerivedArtifact(_CoreValue):
    @property
    def canonical_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def mutation_count(self) -> int: ...
    @property
    def source_field(self) -> int: ...
    @property
    def target_field(self) -> int: ...
class IncompleteArtifactVerification(_CoreValue):
    @property
    def kind(self) -> str: ...
    @property
    def completed(self) -> int | None: ...
    @property
    def field(self) -> str | None: ...
def verify_derived_artifact(text: str, control: ComputationControl | None = ...) -> VerifiedDerivedArtifact | IncompleteArtifactVerification: ...
def build_derived_artifact(algebra: Algebra, mutations: list[tuple[str, int]], field: PrimeField | None = ...) -> str: ...
def run_census(algebra: Algebra, dimensions: list[int], field: PrimeField | None = ..., limits: CensusLimits | None = ..., control: ComputationControl | None = ...) -> CensusCheckpoint: ...
def verify_census_checkpoint(text: str, limits: CensusVerifyLimits | None = ...) -> VerifiedCensusCheckpoint: ...
def start_homological_stream(census: VerifiedCensusCheckpoint, max_degree: int, config: HomologicalStreamConfig | None = ..., control: ComputationControl | None = ...) -> HomologicalCheckpointStream: ...
def verify_homological_checkpoint(text: str, limits: HomologicalStreamVerifyLimits | None = ...) -> VerifiedHomologicalCheckpoint: ...
def build_self_ext_locus_artifact(checkpoint: VerifiedHomologicalCheckpoint, first_degree: int, last_degree: int) -> SelfExtLocusArtifact: ...
def verify_self_ext_locus_artifact(text: str, limits: SelfExtLocusVerifyLimits | None = ...) -> VerifiedSelfExtLocusArtifact: ...
def discover_equivalences(algebra: Algebra, field: PrimeField | None = ..., limits: EquivalenceDiscoveryLimits | None = ..., control: ComputationControl | None = ...) -> IncompleteEquivalenceGraph: ...
def global_dimension(algebra: Algebra, field: PrimeField, bound: int) -> Bounded: ...
def nakayama_indecomposables(algebra: Algebra, field: PrimeField) -> list[tuple[Module, Certificate]]: ...
def dynkin_type(quiver: Quiver) -> DynkinType | None: ...
def euclidean_type(quiver: Quiver) -> EuclideanType | None: ...
def generalized_cartan_matrix(quiver: Quiver) -> list[list[int]] | None: ...
def positive_roots(quiver: Quiver) -> list[list[int]] | None: ...
def dynkin_quiver(diagram: DynkinType) -> Quiver: ...
def euclidean_quiver(diagram: EuclideanType) -> Quiver: ...
def dynkin_indecomposables(algebra: Algebra, field: PrimeField) -> list[tuple[Module, Certificate]]: ...
from ._exceptions import *
