from os import PathLike
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar

from ._core import (
    BarBudgetDiagnostics,
    BarLimits,
    ComputationControl,
    IncompleteArtifactVerification,
    PrimeField,
    TargetLimits,
    _CoreValue,
)

if TYPE_CHECKING:
    from ._algebra import Algebra
    from .explanation import Explanation


DERIVED_INVARIANT_KINDS: tuple[str, ...]


class EquivalenceDiscoveryLimits(_CoreValue):
    def __init__(
        self,
        max_vertices: int = ...,
        max_directed_mutations: int = ...,
        max_total_terms: int = ...,
        max_matrix_entries: int = ...,
        max_hom_spaces: int = ...,
        through_silting: bool = ...,
    ) -> None: ...
    @property
    def max_vertices(self) -> int: ...
    @property
    def max_directed_mutations(self) -> int: ...
    @property
    def max_total_terms(self) -> int: ...
    @property
    def max_matrix_entries(self) -> int: ...
    @property
    def max_hom_spaces(self) -> int: ...
    @property
    def through_silting(self) -> bool: ...


class IncompleteEquivalenceGraph(_CoreValue):
    @property
    def vertex_count(self) -> int: ...
    @property
    def keys(self) -> list[str]: ...
    @property
    def edges(self) -> list[tuple[int, int, str, int]]: ...
    @property
    def blocked(self) -> list[tuple[int, str, int, str]]: ...
    @property
    def stop(self) -> str: ...
    @property
    def completed_mutations(self) -> int: ...
    @property
    def total_terms(self) -> int: ...
    @property
    def matrix_entries(self) -> int: ...
    def verify(self) -> bool: ...


class InvariantLimits(_CoreValue):
    def __init__(
        self, hochschild_degree: int | None = ..., bar: BarLimits | None = ...
    ) -> None: ...
    @property
    def hochschild_degree(self) -> int: ...
    @property
    def bar(self) -> BarLimits: ...


class InvariantReading(_CoreValue):
    @property
    def kind(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def value(self) -> Any: ...
    @property
    def stop(self) -> str | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def bar_diagnostics(self) -> BarBudgetDiagnostics | None: ...
    def separates(self, other: InvariantReading) -> bool: ...


class DerivedInvariants(_CoreValue):
    @property
    def algebra(self) -> Algebra: ...
    @property
    def limits(self) -> InvariantLimits: ...
    @property
    def readings(self) -> list[InvariantReading]: ...
    def reading(self, kind: str) -> InvariantReading: ...
    def first_difference(self, other: DerivedInvariants) -> str | None: ...
    def __getitem__(self, kind: str) -> InvariantReading: ...
    def __len__(self) -> int: ...
    def _repr_html_(self) -> str: ...


class DerivedInequivalenceWitness(_CoreValue):
    def __init__(
        self,
        left: DerivedInvariants,
        right: DerivedInvariants,
        kind: str | None = ...,
    ) -> None: ...
    @property
    def left(self) -> Algebra: ...
    @property
    def right(self) -> Algebra: ...
    @property
    def kind(self) -> str: ...
    @property
    def left_value(self) -> Any: ...
    @property
    def right_value(self) -> Any: ...
    @property
    def limits(self) -> InvariantLimits: ...
    def verify(self) -> bool: ...


class GentleKey(_CoreValue):
    @property
    def vertices(self) -> int: ...
    @property
    def arrows(self) -> list[tuple[int, int]]: ...
    @property
    def relations(self) -> list[tuple[int, int]]: ...
    def algebra(self, field: PrimeField) -> Algebra: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: GentleKey) -> bool: ...
    def __hash__(self) -> int: ...


class GentleDerivedInvariant(_CoreValue):
    @property
    def aag_function(self) -> list[tuple[int, int]]: ...
    @property
    def genus(self) -> int: ...
    @property
    def winding_class(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: GentleDerivedInvariant) -> bool: ...
    def __hash__(self) -> int: ...


class GentleThread(_CoreValue):
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def arrows(self) -> list[int]: ...
    @property
    def sigma(self) -> int: ...
    @property
    def epsilon(self) -> int: ...
    def __len__(self) -> int: ...


class GentlePresentation(_CoreValue):
    @property
    def algebra(self) -> Algebra: ...
    @property
    def relations(self) -> list[tuple[int, int]]: ...
    @property
    def aag_function(self) -> list[tuple[int, int]]: ...
    @property
    def genus(self) -> int: ...
    @property
    def key(self) -> GentleKey: ...
    @property
    def permitted_threads(self) -> list[GentleThread]: ...
    @property
    def forbidden_threads(self) -> list[GentleThread]: ...
    @property
    def full_relation_cycles(self) -> list[list[int]]: ...
    def complete_invariant(self) -> GentleDerivedInvariant: ...


class AlgebraIsomorphism(_CoreValue):
    @staticmethod
    def from_gentle(
        source: Algebra, target: Algebra, field: PrimeField | None = ...
    ) -> AlgebraIsomorphism: ...
    @property
    def source(self) -> Algebra: ...
    @property
    def target(self) -> Algebra: ...
    @property
    def vertex_map(self) -> list[int]: ...
    @property
    def arrow_images(self) -> list[list[int]]: ...
    def verify(self) -> bool: ...


class ClassificationLimits(_CoreValue):
    def __init__(
        self,
        invariants: InvariantLimits | None = ...,
        discovery: EquivalenceDiscoveryLimits | None = ...,
        target: TargetLimits | None = ...,
        through_silting: bool | None = ...,
    ) -> None: ...
    @property
    def invariants(self) -> InvariantLimits: ...
    @property
    def discovery(self) -> EquivalenceDiscoveryLimits: ...
    @property
    def through_silting(self) -> bool: ...
    @property
    def target(self) -> TargetLimits: ...


class DerivedMerge(_CoreValue):
    @property
    def source(self) -> int: ...
    @property
    def member(self) -> int: ...
    @property
    def recipe(self) -> list[tuple[str, int]]: ...
    @property
    def is_duplicate(self) -> bool: ...
    @property
    def recovered_target(self) -> Algebra: ...
    @property
    def isomorphism(self) -> AlgebraIsomorphism: ...


class DerivedClass(_CoreValue):
    @property
    def members(self) -> list[int]: ...
    @property
    def representative(self) -> int: ...
    @property
    def merges(self) -> list[DerivedMerge]: ...
    def __len__(self) -> int: ...


class ClassSeparation(_CoreValue):
    @property
    def classes(self) -> tuple[int, int]: ...
    @property
    def members(self) -> tuple[int, int]: ...
    @property
    def witness(self) -> DerivedInequivalenceWitness: ...


class UnresolvedPair(_CoreValue):
    @property
    def classes(self) -> tuple[int, int]: ...
    @property
    def walks(self) -> list[int]: ...


class MutationWalk(_CoreValue):
    @property
    def member(self) -> int: ...
    @property
    def stop(self) -> str: ...
    @property
    def stop_limit(self) -> int | None: ...
    @property
    def vertices(self) -> int: ...
    @property
    def blocked(self) -> int: ...
    @property
    def examined(self) -> int: ...
    @property
    def target_cuts(self) -> int: ...
    @property
    def unmatched(self) -> int: ...
    @property
    def merges(self) -> int: ...


class DerivedClassification(_CoreValue):
    @property
    def family(self) -> list[Algebra]: ...
    @property
    def limits(self) -> ClassificationLimits: ...
    @property
    def invariants(self) -> list[DerivedInvariants]: ...
    @property
    def groups(self) -> list[list[int]]: ...
    @property
    def classes(self) -> list[DerivedClass]: ...
    @property
    def separations(self) -> list[ClassSeparation]: ...
    @property
    def unresolved(self) -> list[UnresolvedPair]: ...
    @property
    def walks(self) -> list[MutationWalk]: ...
    @property
    def status(self) -> str: ...
    @property
    def verification(self) -> str: ...
    @property
    def fingerprint(self) -> str | None: ...
    def class_of(self, member: int) -> int: ...
    def verify(self) -> bool: ...
    def to_artifact(self) -> DerivedAtlasArtifact: ...
    def export(self, path: str | PathLike[str]) -> Path: ...
    def explain(self) -> Explanation: ...
    def _repr_html_(self) -> str: ...


class DerivedAtlasArtifact(_CoreValue):
    max_input_bytes: ClassVar[int]
    def __init__(self, text: str) -> None: ...
    @property
    def schema(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def engine(self) -> str: ...
    @property
    def field(self) -> int: ...
    @property
    def member_count(self) -> int: ...
    @property
    def class_count(self) -> int: ...
    @property
    def unresolved_count(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def verification(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def has_valid_fingerprint(self) -> bool: ...
    @property
    def canonical_json(self) -> str: ...
    def verify(
        self, control: ComputationControl | None = ...
    ) -> DerivedClassification | IncompleteArtifactVerification: ...


def discover_equivalences(
    algebra: Algebra,
    field: PrimeField | None = ...,
    limits: EquivalenceDiscoveryLimits | None = ...,
    control: ComputationControl | None = ...,
) -> IncompleteEquivalenceGraph: ...
def connected_gentle_keys(vertices: int) -> list[GentleKey]: ...
def connected_gentle_algebras(vertices: int, field: PrimeField) -> list[Algebra]: ...
def classify_derived(
    family: list[Algebra],
    limits: ClassificationLimits | None = ...,
    control: ComputationControl | None = ...,
    field: PrimeField | None = ...,
) -> DerivedClassification: ...
