//! Golden certificate gate: the committed bytes of four certificates must
//! equal this build's output byte for byte, with no trim and no reparse.
//! With the release preflight running `cargo test` on every supported OS,
//! this enforces cross-OS byte identity against one committed reference.
//!
//! The golden files are determinism canaries generated by this library,
//! not independent truth; see `golden-certificates/README.md`. Regenerate
//! them only after a deliberate certificate format change:
//! `GOLDEN_CERT_WRITE=1 cargo test --test golden_cert`.

use std::path::Path;
use std::sync::Arc;

use auslander::algebra::{Algebra, commutative_square, truncated_poly};
use auslander::completion::CompletionLimits;
use auslander::field::PrimeField;
use auslander::quiver::{ArrowId, Quiver};
use auslander::relation::{Presentation, Relation};

mod common;

fn field(p: u64) -> PrimeField {
    PrimeField::new(p).unwrap()
}

fn general(
    num_vertices: u32,
    arrows: &[(u32, u32)],
    p: u64,
    relations: &[&[(i64, &[u32])]],
) -> Arc<Algebra> {
    let field = field(p);
    let quiver = Quiver::new(num_vertices, arrows).unwrap();
    let relations: Vec<Relation> = relations
        .iter()
        .map(|terms| {
            let terms = terms
                .iter()
                .map(|&(c, word)| {
                    (
                        field.elem(c),
                        word.iter().copied().map(ArrowId).collect::<Vec<ArrowId>>(),
                    )
                })
                .collect();
            Relation::new(&quiver, field, terms).unwrap()
        })
        .collect();
    let presentation = Presentation::new(quiver, field, relations).unwrap();
    Algebra::new(presentation, &CompletionLimits::default()).unwrap()
}

/// `k[x]/(x^3)` over F_5: the `truncated-poly-3` oracle family.
fn truncated_poly_3_f5() -> Arc<Algebra> {
    truncated_poly(3, field(5)).unwrap()
}

/// The commutative square with `ab - cd` over F_5: the
/// `commutative-square` oracle family.
fn commutative_square_f5() -> Arc<Algebra> {
    commutative_square(field(5))
}

/// One vertex with loops `x` (0) and `y` (1) over F_2, relations
/// `xx - yy`, `xy`, `yx`: the `self-overlap` oracle family.
fn self_overlap_f2() -> Arc<Algebra> {
    general(
        1,
        &[(0, 0), (0, 0)],
        2,
        &[
            &[(1, &[0, 0]), (-1, &[1, 1])],
            &[(1, &[0, 1])],
            &[(1, &[1, 0])],
        ],
    )
}

fn check(name: &str, committed: &[u8], algebra: &Arc<Algebra>) {
    let bytes = algebra.certificate().to_canonical_json();
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden-certificates")
        .join(name);
    if common::rewrite_golden("GOLDEN_CERT_WRITE", &path, bytes.as_bytes()) {
        return;
    }
    assert_eq!(
        bytes.as_bytes(),
        committed,
        "certificate bytes for {name} differ from the committed golden file"
    );
}

#[test]
fn truncated_poly_3_f5_matches_the_golden_bytes() {
    check(
        "truncated-poly-3-f5.json",
        include_bytes!("golden-certificates/truncated-poly-3-f5.json"),
        &truncated_poly_3_f5(),
    );
}

#[test]
fn commutative_square_f5_matches_the_golden_bytes() {
    check(
        "commutative-square-f5.json",
        include_bytes!("golden-certificates/commutative-square-f5.json"),
        &commutative_square_f5(),
    );
}

#[test]
fn preprojective_a3_f2_matches_the_golden_bytes() {
    check(
        "preprojective-a3-f2.json",
        include_bytes!("golden-certificates/preprojective-a3-f2.json"),
        &common::preprojective_a3(),
    );
}

#[test]
fn self_overlap_f2_matches_the_golden_bytes() {
    check(
        "self-overlap-f2.json",
        include_bytes!("golden-certificates/self-overlap-f2.json"),
        &self_overlap_f2(),
    );
}
