//! Randomized property tests over deterministically seeded xorshift streams.
//!
//! Three generator families, all capped at total dimension [`MAX_TOTAL_DIM`]:
//! (a) direct sums of projectives, simples, and injectives followed by a random
//! vertexwise change of basis; (b) submodules generated by random vertex seeds
//! closed under all arrow actions, built directly from the closure rather than
//! through `kernel`/`image`; (c) quotients by those closed submodules.
//!
//! Basis-change convention, derived once and used throughout: with new
//! coordinates `x'` related to old ones by `x = x'·G_v`, the transformed
//! representation is `M'(a) = G_{s(a)} · M(a) · G_{t(a)}⁻¹`. The vertex matrices
//! `G_v` then form an isomorphism `M' → M`, because the squares
//! `G_{s(a)} · M(a) = M'(a) · G_{t(a)}` hold by construction.
//!
//! Every case prints its seed before asserting, so a failing case reproduces by
//! seeding [`XorShift64`] with the printed value.

use std::sync::Arc;

use auslander::algebra::{
    MonomialAlgebra, an_with_relations, cyclic_nakayama, dual_numbers, linear_an,
};
use auslander::ext::ext_table;
use auslander::field::{Fp, PrimeField};
use auslander::hom::{Morphism, hom, hom_dim, kernel};
use auslander::linalg::DenseMat;
use auslander::module::{Module, direct_sum};
use auslander::quiver::{ArrowId, Quiver};
use auslander::radical::radical;
use auslander::resolution::{ResolutionEnd, projective_cover, resolve};

const MAX_TOTAL_DIM: usize = 12;
/// Cases per (algebra, field) pair. 5 algebras × 2 fields keeps every generator
/// family well under 200 cases.
const CASES: usize = 8;
const SEED_BASE: u64 = 0x0005_eed0_fa05_1a4d;

struct XorShift64(u64);

impl XorShift64 {
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }
}

/// Distinct nonzero seed per (test, field, algebra, case), splittable from the
/// printed value alone.
fn case_seed(test: u64, p: u64, algebra_idx: usize, case: usize) -> u64 {
    let raw = SEED_BASE
        ^ test.wrapping_mul(0x9e37_79b9_7f4a_7c15)
        ^ p.wrapping_mul(0xd1b5_4a32_d192_ed03)
        ^ (algebra_idx as u64).wrapping_mul(0x94d0_49bb_1331_11eb)
        ^ (case as u64).wrapping_mul(0x2545_f491_4f6c_dd1d);
    if raw == 0 { SEED_BASE } else { raw }
}

fn fields() -> [PrimeField; 2] {
    [PrimeField::new(2).unwrap(), PrimeField::new(3).unwrap()]
}

fn gentle_tree() -> Arc<MonomialAlgebra> {
    let quiver = Quiver::new(4, &[(0, 1), (1, 2), (1, 3)]).unwrap();
    MonomialAlgebra::new(quiver, vec![vec![ArrowId(0), ArrowId(1)]]).unwrap()
}

fn algebras() -> Vec<(&'static str, Arc<MonomialAlgebra>)> {
    vec![
        ("linear_an_3", linear_an(3)),
        ("a3_mod_ab", an_with_relations(3, &[(0, 2)]).unwrap()),
        ("gentle_tree", gentle_tree()),
        (
            "cyclic_nakayama_3_3_3",
            cyclic_nakayama(&[3, 3, 3]).unwrap(),
        ),
        ("dual_numbers", dual_numbers()),
    ]
}

fn rand_elem(rng: &mut XorShift64, field: &PrimeField) -> Fp {
    field.elem(rng.below(field.modulus()) as i64)
}

/// Rows stacked into a matrix with an explicit column count, so an empty row
/// list keeps the right width.
fn stacked(rows: &[Vec<Fp>], cols: usize) -> DenseMat {
    let mut out = DenseMat::zero(rows.len(), cols);
    for (r, row) in rows.iter().enumerate() {
        for (c, &v) in row.iter().enumerate() {
            out.set(r, c, v);
        }
    }
    out
}

fn vstack(a: &DenseMat, b: &DenseMat) -> DenseMat {
    let rows: Vec<Vec<Fp>> = (0..a.rows())
        .map(|r| a.row(r).to_vec())
        .chain((0..b.rows()).map(|r| b.row(r).to_vec()))
        .collect();
    stacked(&rows, a.cols())
}

/// Generator (a), first half: a random direct sum of projectives, simples, and
/// injectives with total dimension at most [`MAX_TOTAL_DIM`].
fn random_sum_module(
    rng: &mut XorShift64,
    algebra: &Arc<MonomialAlgebra>,
    field: PrimeField,
) -> Module {
    let n = algebra.quiver().num_vertices();
    let mut parts: Vec<Module> = Vec::new();
    let mut total = 0usize;
    for _ in 0..1 + rng.below(3) {
        let v = rng.below(u64::from(n)) as u32;
        let part = match rng.below(3) {
            0 => Module::simple(algebra, field, v),
            1 => Module::projective(algebra, field, v),
            _ => Module::injective(algebra, field, v),
        };
        if total + part.total_dim() > MAX_TOTAL_DIM {
            break;
        }
        total += part.total_dim();
        parts.push(part);
    }
    if parts.is_empty() {
        parts.push(Module::simple(algebra, field, 0));
    }
    let refs: Vec<&Module> = parts.iter().collect();
    direct_sum(&refs).0
}

/// An invertible `d × d` matrix built from random elementary row operations on
/// the identity.
fn random_invertible(rng: &mut XorShift64, field: &PrimeField, d: usize) -> DenseMat {
    let mut g = DenseMat::identity(d);
    if d == 0 {
        return g;
    }
    for _ in 0..2 * d + 2 {
        let i = rng.below(d as u64) as usize;
        match rng.below(3) {
            0 if d >= 2 => {
                let j = (i + 1 + rng.below(d as u64 - 1) as usize) % d;
                for c in 0..d {
                    let (a, b) = (g.get(i, c), g.get(j, c));
                    g.set(i, c, b);
                    g.set(j, c, a);
                }
            }
            1 => {
                let c = field.elem(1 + rng.below(field.modulus() - 1) as i64);
                for k in 0..d {
                    g.set(i, k, field.mul(g.get(i, k), c));
                }
            }
            _ if d >= 2 => {
                let j = (i + 1 + rng.below(d as u64 - 1) as usize) % d;
                let c = rand_elem(rng, field);
                for k in 0..d {
                    g.set(i, k, field.add(g.get(i, k), field.mul(c, g.get(j, k))));
                }
            }
            _ => {}
        }
    }
    g
}

/// `G⁻¹`, column by column from `G x = e_j`.
fn inverse(g: &DenseMat, field: &PrimeField) -> DenseMat {
    let d = g.rows();
    let mut inv = DenseMat::zero(d, d);
    for j in 0..d {
        let mut unit = vec![field.zero(); d];
        unit[j] = field.one();
        let col = g
            .solve(&unit, field)
            .expect("G is a product of elementary matrices");
        for (i, &v) in col.iter().enumerate() {
            inv.set(i, j, v);
        }
    }
    inv
}

/// Generator (a), second half: `M'(a) = G_{s(a)} · M(a) · G_{t(a)}⁻¹` together
/// with the matrices `G_v`, which form the isomorphism `M' → M`.
fn random_basis_change(rng: &mut XorShift64, m: &Module) -> (Module, Vec<DenseMat>) {
    let field = m.field();
    let quiver = m.algebra().quiver();
    let g: Vec<DenseMat> = m
        .dim_vector()
        .iter()
        .map(|&d| random_invertible(rng, &field, d))
        .collect();
    let g_inv: Vec<DenseMat> = g.iter().map(|x| inverse(x, &field)).collect();
    let maps: Vec<DenseMat> = (0..quiver.num_arrows())
        .map(|i| {
            let a = ArrowId(i as u32);
            let (s, t) = (quiver.source(a) as usize, quiver.target(a) as usize);
            g[s].mul(m.map(a), &field).mul(&g_inv[t], &field)
        })
        .collect();
    let transformed = Module::new(m.algebra().clone(), field, m.dim_vector().to_vec(), maps)
        .expect("a vertexwise basis change preserves the relations");
    (transformed, g)
}

/// Generator (b), closure step: random vertex row-space seeds closed under all
/// arrow actions to a fixed point. Each basis is in reduced row echelon form.
fn random_closed_submodule_bases(rng: &mut XorShift64, m: &Module) -> Vec<DenseMat> {
    let field = m.field();
    let quiver = m.algebra().quiver();
    let n = quiver.num_vertices();
    let mut bases: Vec<DenseMat> = (0..n)
        .map(|v| {
            let d = m.dim_at(v);
            let rows: Vec<Vec<Fp>> = (0..rng.below(3))
                .map(|_| (0..d).map(|_| rand_elem(rng, &field)).collect())
                .collect();
            stacked(&rows, d).row_space_basis(&field)
        })
        .collect();
    loop {
        let mut changed = false;
        for i in 0..quiver.num_arrows() {
            let a = ArrowId(i as u32);
            let (u, v) = (quiver.source(a) as usize, quiver.target(a) as usize);
            let image = bases[u].mul(m.map(a), &field);
            let closed = vstack(&bases[v], &image).row_space_basis(&field);
            if closed.rows() != bases[v].rows() {
                bases[v] = closed;
                changed = true;
            }
        }
        if !changed {
            return bases;
        }
    }
}

/// Coordinates of each row of `vectors` in the row basis `basis`.
fn rows_in_basis(basis: &DenseMat, vectors: &DenseMat, field: &PrimeField) -> DenseMat {
    let bt = basis.transpose();
    let mut out = DenseMat::zero(vectors.rows(), basis.rows());
    for r in 0..vectors.rows() {
        let x = bt
            .solve(vectors.row(r), field)
            .expect("the closure is arrow-invariant, so images lie in the span");
        for (c, &v) in x.iter().enumerate() {
            out.set(r, c, v);
        }
    }
    out
}

/// Generator (b): the submodule carried by closed `bases`, built directly by
/// solving `S(a) · B_{t(a)} = B_{s(a)} · M(a)`, with its inclusion.
fn submodule_from_closure(m: &Module, bases: &[DenseMat]) -> (Module, Morphism) {
    let field = m.field();
    let quiver = m.algebra().quiver();
    let dims: Vec<usize> = bases.iter().map(DenseMat::rows).collect();
    let maps: Vec<DenseMat> = (0..quiver.num_arrows())
        .map(|i| {
            let a = ArrowId(i as u32);
            let (u, v) = (quiver.source(a) as usize, quiver.target(a) as usize);
            rows_in_basis(&bases[v], &bases[u].mul(m.map(a), &field), &field)
        })
        .collect();
    let sub = Module::new(m.algebra().clone(), field, dims, maps)
        .expect("the arrow closure carries a submodule");
    let inclusion =
        Morphism::new(&sub, m, bases.to_vec()).expect("the closure inclusion is A-linear");
    (sub, inclusion)
}

/// Generator (c): the quotient of `m` by the closed submodule, built directly.
///
/// `Q_v = (right kernel of B_v)ᵀ` kills exactly the subspace, and the induced
/// map solves `Q_{s(a)} · C(a) = M(a) · Q_{t(a)}` column by column.
fn quotient_from_closure(m: &Module, bases: &[DenseMat]) -> (Module, Morphism) {
    let field = m.field();
    let quiver = m.algebra().quiver();
    let projections: Vec<DenseMat> = bases
        .iter()
        .map(|b| b.kernel_basis(&field).transpose())
        .collect();
    let dims: Vec<usize> = projections.iter().map(DenseMat::cols).collect();
    let maps: Vec<DenseMat> = (0..quiver.num_arrows())
        .map(|i| {
            let a = ArrowId(i as u32);
            let (u, v) = (quiver.source(a) as usize, quiver.target(a) as usize);
            let rhs = m.map(a).mul(&projections[v], &field);
            let rhs_t = rhs.transpose();
            let mut c = DenseMat::zero(projections[u].cols(), rhs.cols());
            for j in 0..rhs.cols() {
                let x = projections[u]
                    .solve(rhs_t.row(j), &field)
                    .expect("invariance puts each column in the projection's column space");
                for (r, &val) in x.iter().enumerate() {
                    c.set(r, j, val);
                }
            }
            c
        })
        .collect();
    let quotient = Module::new(m.algebra().clone(), field, dims, maps)
        .expect("the quotient by a closed submodule is a module");
    let projection =
        Morphism::new(m, &quotient, projections).expect("the quotient projection is A-linear");
    (quotient, projection)
}

/// Whether every row of `rows` lies in the row space of `basis`.
fn rows_lie_in_row_space(basis: &DenseMat, rows: &DenseMat, field: &PrimeField) -> bool {
    let base_rank = basis.rank(field);
    vstack(basis, rows).rank(field) == base_rank
}

/// `Ext^k` recomputed from generic `hom()` cochain matrices, independent of the
/// Yoneda layout in `ext.rs`: flatten each `Hom(P_i, N)` basis, take ranks of
/// the matrices of `f ↦ d_{i+1} ∘ f` (precomposition, written `d.then(f)`), and
/// read cohomology dimensions off rank-nullity.
fn ext_table_via_generic_hom(m: &Module, n: &Module, max_k: usize) -> Vec<usize> {
    let field = m.field();
    let nv = m.algebra().quiver().num_vertices();
    let res = resolve(m, max_k + 1);
    let bases: Vec<Vec<Morphism>> = res
        .terms
        .iter()
        .map(|t| hom(t, n).expect("resolution terms share algebra and field with n"))
        .collect();
    let flatten = |f: &Morphism| -> Vec<Fp> {
        let mut out = Vec::new();
        for v in 0..nv {
            let map = f.map_at(v);
            for r in 0..map.rows() {
                out.extend_from_slice(map.row(r));
            }
        }
        out
    };
    let h: Vec<usize> = (0..=max_k)
        .map(|i| bases.get(i).map_or(0, Vec::len))
        .collect();
    let ranks: Vec<usize> = (0..=max_k)
        .map(|i| {
            if i + 1 >= res.terms.len() || bases[i].is_empty() {
                return 0;
            }
            let rows: Vec<Vec<Fp>> = bases[i]
                .iter()
                .map(|f| flatten(&res.maps[i].then(f).expect("d targets the term f leaves")))
                .collect();
            DenseMat::from_rows(&rows).rank(&field)
        })
        .collect();
    (0..=max_k)
        .map(|k| {
            let kernel_dim = h[k] - ranks[k];
            let boundary = if k == 0 { 0 } else { ranks[k - 1] };
            assert!(
                kernel_dim >= boundary,
                "δ² != 0 in the generic recomputation"
            );
            kernel_dim - boundary
        })
        .collect()
}

fn for_each_case(
    test: u64,
    mut body: impl FnMut(&mut XorShift64, &Arc<MonomialAlgebra>, PrimeField, &str),
) {
    for field in fields() {
        for (algebra_idx, (name, algebra)) in algebras().iter().enumerate() {
            for case in 0..CASES {
                let seed = case_seed(test, field.modulus(), algebra_idx, case);
                println!(
                    "{name} over F_{} case {case}: seed {seed:#018x}",
                    field.modulus()
                );
                let mut rng = XorShift64(seed);
                body(&mut rng, algebra, field, name);
            }
        }
    }
}

#[test]
fn basis_changed_sums_stay_valid_isomorphic_and_hom_ext_invariant() {
    for_each_case(1, |rng, algebra, field, name| {
        let m = random_sum_module(rng, algebra, field);
        let (t, g) = random_basis_change(rng, &m);
        assert_eq!(t.dim_vector(), m.dim_vector(), "{name}");
        let iso = Morphism::new(&t, &m, g).expect("the G_v matrices form a morphism M' -> M");
        assert!(
            iso.is_isomorphism(),
            "{name}: G_v must be invertible at every vertex"
        );
        let n = algebra.quiver().num_vertices();
        for v in 0..n {
            let s = Module::simple(algebra, field, v);
            assert_eq!(
                hom_dim(&t, &s).unwrap(),
                hom_dim(&m, &s).unwrap(),
                "{name}: dim Hom(-, S_{v}) changed under basis change"
            );
            assert_eq!(
                hom_dim(&s, &t).unwrap(),
                hom_dim(&s, &m).unwrap(),
                "{name}: dim Hom(S_{v}, -) changed under basis change"
            );
        }
        assert_eq!(
            hom_dim(&t, &t).unwrap(),
            hom_dim(&m, &m).unwrap(),
            "{name}: dim End changed under basis change"
        );
        let v = rng.below(u64::from(n)) as u32;
        let s = Module::simple(algebra, field, v);
        assert_eq!(
            ext_table(&t, &s, 2).unwrap(),
            ext_table(&m, &s, 2).unwrap(),
            "{name}: Ext table against S_{v} changed under basis change"
        );
    });
}

#[test]
fn closed_submodules_and_quotients_are_modules_with_exact_dimensions() {
    for_each_case(2, |rng, algebra, field, name| {
        let m = random_sum_module(rng, algebra, field);
        let bases = random_closed_submodule_bases(rng, &m);
        let (sub, inclusion) = submodule_from_closure(&m, &bases);
        let (quotient, projection) = quotient_from_closure(&m, &bases);
        for v in 0..algebra.quiver().num_vertices() {
            assert_eq!(
                sub.dim_at(v) + quotient.dim_at(v),
                m.dim_at(v),
                "{name}: dimensions at vertex {v}"
            );
        }
        let composite = inclusion.then(&projection).expect("shared middle module");
        assert!(composite.is_zero(), "{name}: sub -> m -> m/sub must vanish");
    });
}

#[test]
fn covers_of_random_modules_are_surjective_with_syzygy_in_the_radical() {
    for_each_case(3, |rng, algebra, field, name| {
        let base = random_sum_module(rng, algebra, field);
        let (transformed, _) = random_basis_change(rng, &base);
        let bases = random_closed_submodule_bases(rng, &base);
        let (sub, _) = submodule_from_closure(&base, &bases);
        for m in [&base, &transformed, &sub] {
            let (p, cover) = projective_cover(m);
            let (syzygy, syzygy_inclusion) = kernel(&cover);
            let (_, radical_inclusion) = radical(&p);
            for v in 0..algebra.quiver().num_vertices() {
                assert_eq!(
                    cover.map_at(v).rank(&field),
                    m.dim_at(v),
                    "{name}: cover not surjective at vertex {v}"
                );
                assert!(
                    rows_lie_in_row_space(
                        radical_inclusion.map_at(v),
                        syzygy_inclusion.map_at(v),
                        &field
                    ),
                    "{name}: syzygy escapes rad P at vertex {v} (dim syzygy {})",
                    syzygy.total_dim()
                );
            }
        }
    });
}

#[test]
fn resolution_prefixes_of_random_modules_are_exact_complexes() {
    for_each_case(4, |rng, algebra, field, name| {
        let base = random_sum_module(rng, algebra, field);
        let (transformed, _) = random_basis_change(rng, &base);
        let bases = random_closed_submodule_bases(rng, &base);
        let (sub, _) = submodule_from_closure(&base, &bases);
        let (quotient, _) = quotient_from_closure(&base, &bases);
        for m in [&transformed, &sub, &quotient] {
            let res = resolve(m, 3);
            for v in 0..algebra.quiver().num_vertices() {
                assert_eq!(
                    res.augmentation.map_at(v).rank(&field),
                    m.dim_at(v),
                    "{name}: augmentation not surjective at vertex {v}"
                );
            }
            if let Some(d1) = res.maps.first() {
                assert!(
                    d1.then(&res.augmentation).unwrap().is_zero(),
                    "{name}: aug ∘ d_1 != 0"
                );
            }
            for pair in res.maps.windows(2) {
                assert!(pair[1].then(&pair[0]).unwrap().is_zero(), "{name}: d² != 0");
            }
            for k in 0..res.terms.len() {
                let (ker, _) = if k == 0 {
                    kernel(&res.augmentation)
                } else {
                    kernel(&res.maps[k - 1])
                };
                if k + 1 < res.terms.len() {
                    // dim im d_{k+1} = rank of its vertex matrices.
                    for v in 0..algebra.quiver().num_vertices() {
                        assert_eq!(
                            ker.dim_at(v),
                            res.maps[k].map_at(v).rank(&field),
                            "{name}: exactness fails at P_{k}, vertex {v}"
                        );
                    }
                } else if res.end == ResolutionEnd::Finite {
                    assert!(ker.is_zero(), "{name}: finite resolution must end exactly");
                }
            }
        }
    });
}

#[test]
fn yoneda_ext_agrees_with_generic_hom_cochain_ext() {
    for_each_case(5, |rng, algebra, field, name| {
        let base = random_sum_module(rng, algebra, field);
        let (m, _) = random_basis_change(rng, &base);
        let nv = algebra.quiver().num_vertices();
        let v = rng.below(u64::from(nv)) as u32;
        let targets = [
            Module::simple(algebra, field, v),
            Module::injective(algebra, field, v),
        ];
        for n in &targets {
            assert_eq!(
                ext_table(&m, n, 2).unwrap(),
                ext_table_via_generic_hom(&m, n, 2),
                "{name}: Yoneda and generic-cochain Ext disagree against vertex {v}"
            );
        }
    });
}

#[test]
fn hom_into_an_injective_has_the_dimension_of_the_module_at_its_vertex() {
    for_each_case(6, |rng, algebra, field, name| {
        let base = random_sum_module(rng, algebra, field);
        let (transformed, _) = random_basis_change(rng, &base);
        let bases = random_closed_submodule_bases(rng, &base);
        let (sub, _) = submodule_from_closure(&base, &bases);
        let (quotient, _) = quotient_from_closure(&base, &bases);
        for m in [&base, &transformed, &sub, &quotient] {
            for v in 0..algebra.quiver().num_vertices() {
                let injective = Module::injective(algebra, field, v);
                assert_eq!(
                    hom_dim(m, &injective).unwrap(),
                    m.dim_at(v),
                    "{name}: dim Hom(M, I_{v}) != dim M_{v}"
                );
            }
        }
    });
}
