//! Residue degree above one: where the public API reaches it, and where the
//! tau-tilting layer provably cannot.
//!
//! Residue degree above one is the case an `F_p` basis of `Hom` counts wrong.
//! The multiplicity of `N_i` in a minimal approximation is a dimension over
//! `D_i = End(N_i) / rad End(N_i)`, so with `d_i = dim_{F_p} D_i` an `F_p`
//! basis asks for `d_i` times too many copies. `approx.rs` counts over `D_i`.
//! Its own fixture at `d = 3` is the Kronecker module `(I_3, C)`, which is
//! hereditary and in-module. This binary runs the count from the public API
//! over a non-hereditary algebra at `d = 2`, and pins the reason no mutation
//! and no closed graph can reach the same case.
//!
//! # The obstruction
//!
//! Over a bound quiver algebra `A = kQ/I` with `k` a finite prime field,
//! every tau-rigid indecomposable has residue degree 1.
//!
//! Proof. Let `N` be tau-rigid indecomposable with
//! `End(N) / rad End(N) = L = F_{p^d}`, and base change along `L/k`, which is
//! Galois. `End(N_L) = End(N) tensor_k L` has semisimple quotient
//! `L tensor_k L = L^d`, so `N_L` is a sum of `d` pairwise non-isomorphic
//! indecomposables, and the Galois group permutes them transitively. Base
//! change is exact, carries `P_v` to `P_v tensor L`, and keeps a minimal
//! projective presentation minimal, so it commutes with `tau`. That makes the
//! sum tau-rigid over `A_L`. Twisting by a Galois element is an additive
//! autoequivalence of `mod A_L` that fixes every `P_v tensor L`, so all `d`
//! summands carry one g-vector. Bongartz completion (Adachi, Iyama, and
//! Reiten, Theorem 2.10, section 2, over an arbitrary field) makes the sum a
//! summand of a support tau-tilting pair, and the summands of such a pair
//! carry distinct g-vectors (Demonet, Iyama, and Jasso, arXiv:1503.00285,
//! section 6, over an arbitrary field). Two non-isomorphic summands with one
//! g-vector contradict that, so `d = 1`.
//!
//! The limit of the proof: it needs `k` perfect and `A` split basic. Both
//! hold here. `PrimeField` is a finite prime field, and every algebra this
//! crate builds is `kQ/I` with `I` admissible, so `A / rad A` is `k^n`. The
//! proof also covers the hereditary case, which the Tits form settles on its
//! own.
//!
//! Every approximation generator of the tau-tilting layer is a tau-rigid
//! indecomposable: `mutation.rs` approximates over the summands of `M` minus
//! one slot. So the field generality of the completeness certificate stands,
//! and its residue-degree half stays unexercised: over a prime field no
//! fixture can hand `left_approximation` a generator with `d > 1` from that
//! path. The two walk tests below are that statement in executable form, and
//! one of them runs over an algebra whose module category does hold a `d = 2`
//! brick.
//!
//! Tier: everything here is always-on. Measured on this branch in the dev
//! profile (`opt-level = 2`) on the development host, `--test-threads=1`:
//!
//! ```text
//! the whole binary        0.07 s to 0.11 s over three runs
//! ```
//!
//! A range, not a median, because the host runs other work. The per-test
//! breakdown that once stood here is not restated: it was measured before the
//! closure gate landed, and a stale number reads as a current one.

use std::sync::Arc;

use auslander::algebra::{Algebra, radical_square_zero_cycle};
use auslander::approx::left_approximation;
use auslander::basic::{BasicDecomposition, ProjectiveSupport};
use auslander::completion::CompletionLimits;
use auslander::ext::ext_dim;
use auslander::homspace::HomSpace;
use auslander::indec::IndecomposableModule;
use auslander::linalg::DenseMat;
use auslander::module::{Module, direct_sum};
use auslander::quiver::Quiver;
use auslander::relation::{Presentation, Relation};
use auslander::supporttau::{PairRejection, SupportTauTiltingPair};
use auslander::taugraph::{
    MutationGraphLimits, SupportTauTiltingGraphOutcome, VerifiedMutation, support_tau_tilting_graph,
};
use auslander::taurigid::{TauRigidityOutcome, is_tau_rigid};

mod common;

use common::{f2, ids};

/// The algebra `kQ/I` over F_2. `Q` carries the arrows `a, b: 0 -> 1` with
/// ids 0 and 1, and `c, d: 1 -> 2` with ids 2 and 3. `I` is generated by
/// `a·c + b·d` and `a·d + b·c + b·d`. Dimension 9: 3 idempotents, 4 arrows,
/// and 2 of the 4 paths of length two.
///
/// `I` is admissible. Both relations lie in `rad^2`, and `Q` has no path of
/// length three, so `rad^3` is zero. `I` is not zero, so the algebra is not
/// hereditary.
///
/// The name comes from the modules of dimension vector (1, 1, 1) over an
/// extension of F_2. Normalize `a` and `c` to 1. The first relation then
/// reads `b·d = 1` and the second `d = b + 1`, so `b` is a root of
/// `x^2 + x + 1`. Both roots lie in F_4 and neither in F_2, and the two are
/// conjugate over F_2. That is what gives [`residue_degree_two_brick`] its
/// residue degree, and it is specific to F_2: over F_5 the same relations
/// read `b·d = -1` and `d = 1 - b`, whose only solution is the rational
/// double root 3.
fn conjugate_root_algebra() -> Arc<Algebra> {
    let field = f2();
    let quiver =
        Quiver::new(3, &[(0, 1), (0, 1), (1, 2), (1, 2)]).expect("the targets are in range");
    let one = field.one();
    let relations = vec![
        Relation::new(
            &quiver,
            field,
            vec![(one, ids(&[0, 2])), (one, ids(&[1, 3]))],
        )
        .expect("both words are paths from 0 to 2"),
        Relation::new(
            &quiver,
            field,
            vec![
                (one, ids(&[0, 3])),
                (one, ids(&[1, 2])),
                (one, ids(&[1, 3])),
            ],
        )
        .expect("all three words are paths from 0 to 2"),
    ];
    let presentation =
        Presentation::new(quiver, field, relations).expect("both relations have length two");
    Algebra::new(presentation, &CompletionLimits::default())
        .expect("a quiver with no path of length three completes")
}

/// Multiplication by `omega` on `F_4 = F_2[omega]/(omega^2 + omega + 1)`, in
/// the basis `1, omega`, on row vectors.
fn omega() -> DenseMat {
    let field = f2();
    let mut m = DenseMat::zero(2, 2);
    m.set(0, 1, field.one());
    m.set(1, 0, field.one());
    m.set(1, 1, field.one());
    m
}

/// Multiplication by `omega + 1`, the other root of `x^2 + x + 1`.
fn omega_plus_one() -> DenseMat {
    let field = f2();
    let mut m = DenseMat::zero(2, 2);
    m.set(0, 0, field.one());
    m.set(0, 1, field.one());
    m.set(1, 0, field.one());
    m
}

/// The F_2 form of the (1, 1, 1)-dimensional F_4 module over
/// [`conjugate_root_algebra`] with `a = c = 1`, `b = omega`, and
/// `d = omega + 1`.
///
/// Each vertex carries F_4 as a 2-dimensional F_2 space, so the dimension
/// vector is (2, 2, 2) and `End` holds F_4. Once `a` and `c` are normalized,
/// `b` is an invariant of the isomorphism class, so the module and its
/// conjugate stay apart over F_4, `End` is exactly F_4, and the residue
/// degree is 2. Every test that uses this module asserts that degree instead
/// of assuming it.
fn residue_degree_two_brick(algebra: &Arc<Algebra>) -> Module {
    Module::new(
        algebra.clone(),
        vec![2, 2, 2],
        vec![
            DenseMat::identity(2),
            omega(),
            DenseMat::identity(2),
            omega_plus_one(),
        ],
    )
    .expect("both relations annihilate the module")
}

#[test]
fn the_conjugate_root_algebra_is_not_hereditary_and_holds_a_residue_degree_two_brick() {
    let algebra = conjugate_root_algebra();
    assert_eq!(algebra.dim(), 9);

    // dim Ext^2(S_0, S_2) counts the relations from vertex 0 to vertex 2,
    // which is 2 here. A hereditary algebra has no Ext above degree 1, so
    // this is the non-hereditary half of the fixture by value.
    let s0 = Module::simple(&algebra, 0);
    let s2 = Module::simple(&algebra, 2);
    assert_eq!(ext_dim(&s0, &s2, 2).unwrap(), 2);

    let brick = residue_degree_two_brick(&algebra);
    let certified = IndecomposableModule::new(&brick).unwrap();
    assert_eq!(certified.residue_degree(), 2, "the fixture must have d = 2");
    assert_eq!(certified.endo().dim(), 2);
    assert_eq!(certified.endo().radical_dim(), 0, "End is the field F_4");
    assert!(!certified.is_projective());
}

#[test]
fn a_left_approximation_by_the_residue_degree_two_brick_halves_the_fp_count() {
    let algebra = conjugate_root_algebra();
    let brick = residue_degree_two_brick(&algebra);

    // Hom(N (+) P_0, N) has F_2 dimension 4: End(N) = F_4 gives 2, and
    // Hom(P_0, N) = N_0 gives 2 more. Over D = F_4 that is 2 generators, so
    // the minimal left approximation takes 2 copies of N. An F_2 basis would
    // ask for 4. That overcount is the defect this test catches.
    let sum = direct_sum(&[&brick, &Module::projective(&algebra, 0)]).0;
    let fp_dim = HomSpace::new(&sum, &brick).unwrap().dim();
    assert_eq!(fp_dim, 4);

    let approximation = left_approximation(&sum, std::slice::from_ref(&brick)).unwrap();
    assert_eq!(
        approximation.summands()[0].residue_degree(),
        2,
        "the generator must have d = 2"
    );
    assert_eq!(approximation.multiplicity(0), fp_dim / 2);
    assert!(approximation.verify());
}

#[test]
fn the_residue_degree_two_brick_fails_the_tau_rigidity_condition_of_a_pair() {
    let algebra = conjugate_root_algebra();
    let brick = residue_degree_two_brick(&algebra);
    assert_eq!(
        IndecomposableModule::new(&brick).unwrap().residue_degree(),
        2,
        "the fixture must have d = 2"
    );

    let outcome = is_tau_rigid(&brick).unwrap();
    let TauRigidityOutcome::NotTauRigid(witness) = &outcome else {
        panic!("the obstruction puts every tau-rigid indecomposable at d = 1")
    };
    assert!(witness.verify());

    // Condition 3 of design section 6. This is the gate that keeps a residue
    // degree above one out of every pair, and so out of every approximation
    // the mutation layer runs.
    let module = BasicDecomposition::new(&brick).unwrap();
    let projective = ProjectiveSupport::new(&algebra, &[]).unwrap();
    let classification = SupportTauTiltingPair::classify(module, projective).unwrap();
    let rejection = classification.rejection().expect("the brick is not a pair");
    assert_eq!(rejection.condition(), 3);
    assert!(matches!(rejection, PairRejection::NotTauRigid(_)));
}

/// The residue degrees the approximation generators of `mutations` take, and
/// how many generators were read.
///
/// Callers assert that the count is positive, so an empty walk cannot pass.
fn generator_degrees(mutations: &[VerifiedMutation]) -> (Vec<usize>, usize) {
    let mut degrees = Vec::new();
    let mut counted = 0;
    for mutation in mutations {
        for summand in mutation.mutation().witness().approximation().summands() {
            counted += 1;
            let degree = summand.residue_degree();
            if !degrees.contains(&degree) {
                degrees.push(degree);
            }
        }
    }
    degrees.sort_unstable();
    (degrees, counted)
}

#[test]
fn no_approximation_generator_over_the_conjugate_root_algebra_has_residue_degree_two() {
    let algebra = conjugate_root_algebra();
    // The walk over this algebra does not close. Under the default budget it
    // reached 50 vertices before the work-unit ceiling stopped it, so the cap
    // here holds the cost down. A truncated walk carries verified mutations
    // all the same, and the check reads either outcome.
    let limits = MutationGraphLimits {
        max_vertices: 16,
        ..MutationGraphLimits::default()
    };
    let outcome = support_tau_tilting_graph(&algebra, &limits)
        .expect("a budget stop is an outcome, not an error");
    let (degrees, counted) = match &outcome {
        SupportTauTiltingGraphOutcome::Closed(graph) => {
            assert!(graph.verify());
            generator_degrees(graph.mutations())
        }
        SupportTauTiltingGraphOutcome::Incomplete(partial) => {
            assert!(partial.verify_parts());
            generator_degrees(partial.verified_mutations())
        }
    };
    assert!(counted > 0, "a walk with no generator proves nothing");
    assert_eq!(degrees, vec![1]);
}

#[test]
fn no_approximation_generator_of_a_closed_graph_has_residue_degree_two() {
    let algebra = radical_square_zero_cycle(3, f2());
    let outcome = support_tau_tilting_graph(&algebra, &MutationGraphLimits::default()).unwrap();
    let SupportTauTiltingGraphOutcome::Closed(graph) = outcome else {
        panic!("the 3-cycle with rad^2 = 0 closes on 14 pairs")
    };
    assert!(graph.verify());

    let (degrees, counted) = generator_degrees(graph.mutations());
    assert!(counted > 0, "a graph with no generator proves nothing");
    assert_eq!(degrees, vec![1]);
}
